import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";

export const EMPLOYEE_STUDIO_CONTRACT = "employee-studio-v1" as const;
export type StudioBinding = { projectId: string; runtimeId: string; runtimeAssignmentId: string; profileId: string; actorId: string };
export type StudioCapabilityState = { available: boolean; reason: "READY" | "SETUP_REQUIRED" | "UNAVAILABLE" };
export type StudioCapabilities = { contractVersion: typeof EMPLOYEE_STUDIO_CONTRACT; binding: StudioBinding; model: StudioCapabilityState; profileFiles: StudioCapabilityState; skills: StudioCapabilityState; skillLifecycle: StudioCapabilityState; mcp: StudioCapabilityState; observedAt: string };
export type StudioModel = { provider: string; modelId: string; displayName: string; setupState: "READY" | "SETUP_REQUIRED" | "UNAVAILABLE" };
export type StudioModelCatalog = { contractVersion: typeof EMPLOYEE_STUDIO_CONTRACT; binding: StudioBinding; revision: string; expiresAt: string; current: { provider: string; modelId: string; revision: number; fingerprint: string } | null; models: StudioModel[]; signature: string };
export type StudioMutationReceipt = { contractVersion: typeof EMPLOYEE_STUDIO_CONTRACT; binding: StudioBinding; mutationId: string; receiptId: string; status: "APPLIED" | "ROLLED_BACK"; observed: Record<string, unknown>; observedFingerprint: string; completedAt: string };
export type StudioProfileFileDescriptor = { logicalKey: string; displayName: string; editable: boolean; version: number; digest: string; byteLength: number };
export type StudioProfileFile = StudioProfileFileDescriptor & { content: string };
export type StudioSkill = { key: string; name: string; version: string; installed: boolean; enabled: boolean; readable: boolean; digest: string | null; content: string | null };
export type StudioMcpServer = { serverKey: string; displayName: string; setupState: "READY" | "SETUP_REQUIRED" | "UNAVAILABLE"; toolKeys: string[] };
export type EmployeeStudioAdapter = {
  capabilities(binding: StudioBinding): Promise<StudioCapabilities>;
  modelCatalog(binding: StudioBinding): Promise<StudioModelCatalog>;
  changeModel(input: { binding: StudioBinding; mutationId: string; catalogRevision: string; expectedRevision: number; expectedFingerprint: string | null; provider: string; modelId: string; observedModelId: string }): Promise<StudioMutationReceipt>;
  rollbackModel(input: { binding: StudioBinding; mutationId: string; receiptId: string; expectedRevision: number; provider: string; modelId: string; observedModelId: string }): Promise<StudioMutationReceipt>;
  listProfileFiles(binding: StudioBinding): Promise<StudioProfileFileDescriptor[]>;
  readProfileFile(binding: StudioBinding, logicalKey: string): Promise<StudioProfileFile>;
  writeProfileFile(input: { binding: StudioBinding; mutationId: string; logicalKey: string; expectedVersion: number; expectedDigest: string; content: string }): Promise<StudioMutationReceipt>;
  restoreProfileFile(input: { binding: StudioBinding; mutationId: string; logicalKey: string; expectedVersion: number; expectedDigest: string; restoreVersion: number }): Promise<StudioMutationReceipt>;
  listSkills(binding: StudioBinding): Promise<StudioSkill[]>;
  reconcileSkill(input: { binding: StudioBinding; mutationId: string; skillKey: string; version: string; enabled: boolean }): Promise<StudioMutationReceipt>;
  rollbackSkill(input: { binding: StudioBinding; mutationId: string; receiptId: string; skillKey: string; version: string; enabled: boolean }): Promise<StudioMutationReceipt>;
  listMcpServers(binding: StudioBinding): Promise<StudioMcpServer[]>;
  reconcileMcp(input: { binding: StudioBinding; mutationId: string; serverKey: string; enabled: boolean; secretReferenceId: string; toolKeys: string[] }): Promise<StudioMutationReceipt>;
  rollbackMcp(input: { binding: StudioBinding; mutationId: string; receiptId: string; serverKey: string; enabled: boolean; secretReferenceId: string | null; toolKeys: string[] }): Promise<StudioMutationReceipt>;
};

const opaque = /^[A-Za-z0-9_-]{8,160}$/, safe = /^[A-Za-z0-9][A-Za-z0-9_.:/-]{0,239}$/, sha = /^[a-f0-9]{64}$/;
const logicalFiles = ["identity", "preferences", "instructions", "memory"] as const;
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
function exact(value: Record<string, unknown>, keys: string[], code: string) { const actual = Object.keys(value).sort(), expected = [...keys].sort(); if (actual.length !== expected.length || actual.some((item, index) => item !== expected[index])) throw new Error(code); }
function text(value: unknown, max: number, pattern?: RegExp): value is string { return typeof value === "string" && value.length > 0 && value.length <= max && (!pattern || pattern.test(value)); }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (isRecord(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`; if (typeof value === "number" && !Number.isFinite(value)) throw new Error("EMPLOYEE_STUDIO_INVALID_NUMBER"); return JSON.stringify(value); }
function studioState(value: unknown) { if (!["READY", "SETUP_REQUIRED", "UNAVAILABLE"].includes(String(value))) throw new Error("EMPLOYEE_STUDIO_MALFORMED_STATE"); const reason = value as StudioCapabilityState["reason"]; return { available: reason === "READY", reason }; }

export function validateStudioBinding(binding: StudioBinding) { if (![binding.projectId, binding.runtimeId, binding.runtimeAssignmentId, binding.actorId].every((value) => opaque.test(value)) || !safe.test(binding.profileId)) throw new Error("EMPLOYEE_STUDIO_INVALID_BINDING"); return binding; }
function identity(value: Record<string, unknown>, binding: StudioBinding, keys: string[]) { exact(value, ["contractVersion", "projectId", "runtimeId", "runtimeAssignmentId", "profileId", ...keys], "EMPLOYEE_STUDIO_MALFORMED_RESPONSE"); if (value.contractVersion !== EMPLOYEE_STUDIO_CONTRACT || value.projectId !== binding.projectId || value.runtimeId !== binding.runtimeId || value.runtimeAssignmentId !== binding.runtimeAssignmentId || value.profileId !== binding.profileId) throw new Error("EMPLOYEE_STUDIO_BINDING_MISMATCH"); }
export function parseStudioCapabilities(value: unknown, binding: StudioBinding): StudioCapabilities { if (!isRecord(value)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); identity(value, binding, ["capabilities"]); if (!Array.isArray(value.capabilities) || value.capabilities.length !== 5) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); const states = new Map<string, StudioCapabilityState>(); for (const item of value.capabilities) { if (!isRecord(item)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); exact(item, ["name", "state"], "EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); if (!["models", "profileFiles", "skills", "skillLifecycle", "mcp"].includes(String(item.name)) || states.has(String(item.name))) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); states.set(String(item.name), studioState(item.state)); } return { contractVersion: EMPLOYEE_STUDIO_CONTRACT, binding, model: states.get("models")!, profileFiles: states.get("profileFiles")!, skills: states.get("skills")!, skillLifecycle: states.get("skillLifecycle")!, mcp: states.get("mcp")!, observedAt: new Date().toISOString() }; }

export function studioCatalogSignatureBody(binding: StudioBinding, value: Pick<StudioModelCatalog, "revision" | "expiresAt" | "current" | "models">) { return JSON.stringify({ binding, current: value.current, expiresAt: value.expiresAt, models: value.models, revision: value.revision }); }
export function parseStudioModelCatalog(value: unknown, binding: StudioBinding, secret: string, now = Date.now()): StudioModelCatalog { if (!isRecord(value)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); identity(value, binding, ["catalog", "signature"]); if (!isRecord(value.catalog) || !text(value.signature, 64, sha)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); exact(value.catalog, ["models", "revision", "expiresAt", "expired"], "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); if (!Array.isArray(value.catalog.models) || value.catalog.models.length > 100 || !Number.isSafeInteger(value.catalog.revision) || !Number.isSafeInteger(value.catalog.expiresAt) || typeof value.catalog.expired !== "boolean") throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); const unsigned = { contractVersion: EMPLOYEE_STUDIO_CONTRACT, projectId: binding.projectId, runtimeId: binding.runtimeId, runtimeAssignmentId: binding.runtimeAssignmentId, profileId: binding.profileId, catalog: value.catalog }; const expected = createHmac("sha256", secret).update(JSON.stringify(unsigned)).digest(), supplied = Buffer.from(value.signature, "hex"); if (expected.length !== supplied.length || !timingSafeEqual(expected, supplied)) throw new Error("EMPLOYEE_STUDIO_MODEL_CATALOG_SIGNATURE_INVALID"); const expires = Number(value.catalog.expiresAt); if (value.catalog.expired || expires <= now || expires > now + 600_000) throw new Error("EMPLOYEE_STUDIO_STALE_MODEL_CATALOG"); const models = value.catalog.models.map((item) => { if (!isRecord(item)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); exact(item, ["id", "state"], "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); if (!text(item.id, 240, safe)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); const state = studioState(item.state).reason; return { provider: "hermes", modelId: item.id, displayName: item.id, setupState: state }; }); if (new Set(models.map((item) => item.modelId)).size !== models.length) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); return { contractVersion: EMPLOYEE_STUDIO_CONTRACT, binding, revision: String(value.catalog.revision), expiresAt: new Date(expires).toISOString(), current: null, models, signature: value.signature }; }
export function parseStudioMutationReceipt(value: unknown, binding: StudioBinding, mutationId: string): StudioMutationReceipt {
  if (!isRecord(value)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); identity(value, binding, ["receipt"]);
  if (!isRecord(value.receipt) || JSON.stringify(value.receipt).length > 4096 || /secret|token|password|credential|path|command/i.test(JSON.stringify(value.receipt))) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
  const receipt = value.receipt, observed: Record<string, unknown> = {};
  if (receipt.kind === "MODEL_UPDATED") {
    exact(receipt, ["kind", "modelId", "previousModelId", "revision", "confirmed"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    if (!text(receipt.modelId, 240, safe) || !text(receipt.previousModelId, 240, safe) || !Number.isSafeInteger(receipt.revision) || receipt.confirmed !== true) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    Object.assign(observed, { provider: "hermes", modelId: receipt.modelId, revision: receipt.revision });
  } else if (receipt.kind === "MODEL_ROLLBACK") {
    exact(receipt, ["kind", "requestedModelId", "restoredModelId", "revision", "confirmed"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    if (!text(receipt.requestedModelId, 240, safe) || !text(receipt.restoredModelId, 240, safe) || !Number.isSafeInteger(receipt.revision) || receipt.confirmed !== false) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    Object.assign(observed, { provider: "hermes", modelId: receipt.restoredModelId, revision: receipt.revision });
  } else if (receipt.kind === "PROFILE_FILE_UPDATED") {
    exact(receipt, ["kind", "profileId", "key", "revision", "digest", "previousDigest"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    if (receipt.profileId !== binding.profileId || !isAllowedProfileFileKey(String(receipt.key)) || !Number.isSafeInteger(receipt.revision) || !text(receipt.digest, 64, sha) || !text(receipt.previousDigest, 64, sha)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    Object.assign(observed, { logicalKey: receipt.key, digest: receipt.digest, version: receipt.revision });
  } else if (receipt.kind === "PROFILE_FILE_RESTORED") {
    exact(receipt, ["kind", "profileId", "key", "restoredFromRevision", "revision", "digest"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    if (receipt.profileId !== binding.profileId || !isAllowedProfileFileKey(String(receipt.key)) || !Number.isSafeInteger(receipt.restoredFromRevision) || !Number.isSafeInteger(receipt.revision) || !text(receipt.digest, 64, sha)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
    Object.assign(observed, { logicalKey: receipt.key, digest: receipt.digest, version: receipt.revision });
  } else throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT");
  const receiptId = createHash("sha256").update(canonical(receipt)).digest("hex");
  return { contractVersion: EMPLOYEE_STUDIO_CONTRACT, binding, mutationId, receiptId, status: receipt.kind === "MODEL_ROLLBACK" ? "ROLLED_BACK" : "APPLIED", observed, observedFingerprint: createHash("sha256").update(canonical(observed)).digest("hex"), completedAt: new Date().toISOString() };
}

export function isAllowedProfileFileKey(value: string) { return (logicalFiles as readonly string[]).includes(value); }
const baseUrl = () => process.env.ROGEROS_EMPLOYEE_STUDIO_ADAPTER_URL?.replace(/\/$/, ""), token = () => process.env.ROGEROS_EMPLOYEE_STUDIO_ADAPTER_TOKEN, requestSecret = () => process.env.ROGEROS_EMPLOYEE_STUDIO_HMAC_SECRET, catalogSecret = () => process.env.ROGEROS_EMPLOYEE_STUDIO_CATALOG_HMAC_SECRET;
export function employeeStudioAdapterConfigured() { return process.env.ROGEROS_EMPLOYEE_STUDIO_ENABLED === "true" && Boolean(baseUrl() && token() && requestSecret() && catalogSecret()); }
async function request(path: string, operation: string, binding: StudioBinding, payload: Record<string, unknown>, control: { idempotencyKey?: string; expectedRevision?: number | null; expectedFingerprint?: string | null } = {}) { const base = baseUrl(), auth = token(), secret = requestSecret(); if (!employeeStudioAdapterConfigured() || !base || !auth || !secret) throw new Error("EMPLOYEE_STUDIO_NOT_CONFIGURED"); validateStudioBinding(binding); const unsigned = { contractVersion: EMPLOYEE_STUDIO_CONTRACT, ...binding, timestamp: Date.now(), nonce: randomBytes(24).toString("base64url"), idempotencyKey: control.idempotencyKey || `read_${randomBytes(18).toString("base64url")}`, expectedRevision: control.expectedRevision ?? null, expectedFingerprint: control.expectedFingerprint ?? null, operation, payload }; const body = JSON.stringify({ ...unsigned, signature: createHmac("sha256", secret).update(canonical(unsigned)).digest("hex") }); const response = await fetch(`${base}/v1${path}`, { method: "POST", cache: "no-store", redirect: "error", headers: { Authorization: `Bearer ${auth}`, "Content-Type": "application/json" }, body }); if (!response.ok) throw new Error(`EMPLOYEE_STUDIO_ADAPTER_${response.status}`); return response.json() as Promise<unknown>; }
async function currentModel(binding: StudioBinding) { const value = await request("/models/read", "MODEL_READ", binding, {}); if (!isRecord(value)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL"); identity(value, binding, ["model"]); if (!isRecord(value.model)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL"); exact(value.model, ["id", "revision"], "EMPLOYEE_STUDIO_MALFORMED_MODEL"); if (!text(value.model.id, 240, safe) || !Number.isSafeInteger(value.model.revision)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL"); return { provider: "hermes", modelId: value.model.id, revision: Number(value.model.revision), fingerprint: createHash("sha256").update(`${value.model.id}:${value.model.revision}`).digest("hex") }; }
async function profileFile(binding: StudioBinding, logicalKey: string): Promise<StudioProfileFile> { if (!isAllowedProfileFileKey(logicalKey)) throw new Error("EMPLOYEE_STUDIO_FILE_NOT_ALLOWED"); const value = await request("/profile-files/read", "PROFILE_FILE_READ", binding, { key: logicalKey }); if (!isRecord(value)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); identity(value, binding, ["file"]); if (!isRecord(value.file)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); exact(value.file, ["key", "content", "digest", "revision"], "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); if (value.file.key !== logicalKey || typeof value.file.content !== "string" || Buffer.byteLength(value.file.content, "utf8") > 65_536 || !text(value.file.digest, 64, sha) || !Number.isSafeInteger(value.file.revision) || createHash("sha256").update(value.file.content).digest("hex") !== value.file.digest) throw new Error("EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); return { logicalKey, displayName: logicalKey, editable: true, version: Number(value.file.revision), digest: value.file.digest, byteLength: Buffer.byteLength(value.file.content, "utf8"), content: value.file.content }; }
async function inventory(binding: StudioBinding): Promise<StudioSkill[]> { const value = await request("/skills/inventory", "SKILL_INVENTORY", binding, {}); if (!isRecord(value)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_SKILLS"); identity(value, binding, ["inventory"]); if (!isRecord(value.inventory) || !Array.isArray(value.inventory.skills) || value.inventory.skills.length > 100) throw new Error("EMPLOYEE_STUDIO_MALFORMED_SKILLS"); return value.inventory.skills.map((item) => { if (!isRecord(item)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_SKILLS"); exact(item, ["id", "state", "version"], "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); if (!text(item.id, 120, safe) || !text(item.version, 80, safe) || !["AVAILABLE", "ENABLED", "DISABLED", "UNAVAILABLE"].includes(String(item.state))) throw new Error("EMPLOYEE_STUDIO_MALFORMED_SKILLS"); return { key: item.id, name: item.id, version: item.version, installed: item.state !== "UNAVAILABLE", enabled: item.state === "ENABLED", readable: item.state !== "UNAVAILABLE", digest: null, content: null }; }); }

export const employeeStudioAdapter: EmployeeStudioAdapter = {
  capabilities: async (binding) => parseStudioCapabilities(await request("/capabilities", "CAPABILITIES", binding, {}), binding),
  modelCatalog: async (binding) => { const parsed = parseStudioModelCatalog(await request("/models/catalog", "MODEL_CATALOG", binding, {}), binding, catalogSecret() || ""); return { ...parsed, current: await currentModel(binding) }; },
  changeModel: async (input) => parseStudioMutationReceipt(await request("/models/set", "MODEL_SET", input.binding, { modelId: input.modelId, observedModelId: input.observedModelId }, { idempotencyKey: input.mutationId, expectedRevision: input.expectedRevision, expectedFingerprint: input.expectedFingerprint }), input.binding, input.mutationId),
  rollbackModel: async (input) => { const receipt = parseStudioMutationReceipt(await request("/models/set", "MODEL_SET", input.binding, { modelId: input.modelId, observedModelId: input.modelId }, { idempotencyKey: `${input.mutationId}.rollback`, expectedRevision: input.expectedRevision }), input.binding, input.mutationId); return { ...receipt, status: "ROLLED_BACK" }; },
  listProfileFiles: async (binding) => Promise.all(logicalFiles.map(async (key) => { const { content: _content, ...file } = await profileFile(binding, key); void _content; return file; })), readProfileFile: profileFile,
  writeProfileFile: async (input) => parseStudioMutationReceipt(await request("/profile-files/update", "PROFILE_FILE_UPDATE", input.binding, { key: input.logicalKey, content: input.content }, { idempotencyKey: input.mutationId, expectedRevision: input.expectedVersion, expectedFingerprint: input.expectedDigest }), input.binding, input.mutationId),
  restoreProfileFile: async (input) => parseStudioMutationReceipt(await request("/profile-files/restore", "PROFILE_FILE_RESTORE", input.binding, { key: input.logicalKey, backupRevision: input.restoreVersion }, { idempotencyKey: input.mutationId, expectedRevision: input.expectedVersion, expectedFingerprint: input.expectedDigest }), input.binding, input.mutationId),
  listSkills: inventory,
  reconcileSkill: async (input) => parseStudioMutationReceipt(await request("/skills/lifecycle", "SKILL_LIFECYCLE", input.binding, { skillId: input.skillKey, action: input.enabled ? "ENABLE" : "DISABLE" }, { idempotencyKey: input.mutationId }), input.binding, input.mutationId),
  rollbackSkill: async () => { throw new Error("EMPLOYEE_STUDIO_SKILL_LIFECYCLE_UNAVAILABLE"); },
  listMcpServers: async (binding) => { await request("/mcp", "MCP", binding, {}); return []; },
  reconcileMcp: async () => { throw new Error("EMPLOYEE_STUDIO_MCP_UNAVAILABLE"); }, rollbackMcp: async () => { throw new Error("EMPLOYEE_STUDIO_MCP_UNAVAILABLE"); },
};
