import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";

export const EMPLOYEE_STUDIO_CONTRACT = "employee-studio-v1" as const;
export const STUDIO_PROFILE_KEYS = ["identity", "preferences", "instructions", "memory"] as const;
type SetupState = "READY" | "SETUP_REQUIRED" | "UNAVAILABLE";
export type StudioBinding = { projectId: string; runtimeId: string; runtimeAssignmentId: string; profileId: string; actorId: string };
export type StudioCapabilityState = { available: boolean; reason: SetupState };
export type StudioCapabilities = { contractVersion: typeof EMPLOYEE_STUDIO_CONTRACT; binding: StudioBinding; model: StudioCapabilityState; profileFiles: StudioCapabilityState; skills: StudioCapabilityState; skillLifecycle: StudioCapabilityState; mcp: StudioCapabilityState; observedAt: string };
export type StudioModel = { provider: string; modelId: string; displayName: string; setupState: SetupState };
export type StudioModelCatalog = { contractVersion: typeof EMPLOYEE_STUDIO_CONTRACT; binding: StudioBinding; revision: string; expiresAt: string; current: { provider: string; modelId: string; revision: number } | null; models: StudioModel[] };
export type StudioMutationReceipt = { contractVersion: typeof EMPLOYEE_STUDIO_CONTRACT; binding: StudioBinding; mutationId: string; receiptId: string; status: "APPLIED" | "ROLLED_BACK"; observed: Record<string, unknown>; observedFingerprint: string; completedAt: string };
export type StudioProfileFileDescriptor = { logicalKey: string; displayName: string; editable: boolean; version: number; digest: string; byteLength: number };
export type StudioProfileFile = StudioProfileFileDescriptor & { content: string };
export type StudioSkill = { key: string; name: string; version: string; installed: boolean; enabled: boolean; readable: boolean; digest: string | null; content: string | null };
export type StudioMcpServer = { serverKey: string; displayName: string; setupState: SetupState; toolKeys: string[] };
export type EmployeeStudioAdapter = {
  capabilities(binding: StudioBinding): Promise<StudioCapabilities>;
  modelCatalog(binding: StudioBinding): Promise<StudioModelCatalog>;
  changeModel(input: { binding: StudioBinding; mutationId: string; catalogRevision: string; expectedRevision: number; expectedFingerprint: string | null; provider: string; modelId: string; observedModelId: string }): Promise<StudioMutationReceipt>;
  rollbackModel(input: { binding: StudioBinding; mutationId: string; receiptId: string; expectedRevision: number; provider: string; modelId: string; observedModelId: string }): Promise<StudioMutationReceipt>;
  listProfileFiles(binding: StudioBinding): Promise<StudioProfileFileDescriptor[]>;
  readProfileFile(binding: StudioBinding, logicalKey: string): Promise<StudioProfileFile>;
  writeProfileFile(input: { binding: StudioBinding; mutationId: string; logicalKey: string; expectedVersion: number; expectedDigest: string; content: string }): Promise<StudioMutationReceipt>;
  restoreProfileFile(input: { binding: StudioBinding; mutationId: string; logicalKey: string; expectedVersion: number; expectedDigest: string; restoreVersion: number }): Promise<StudioMutationReceipt>;
  listSkills(binding: StudioBinding): Promise<StudioSkill[]>;
  listMcpServers(binding: StudioBinding): Promise<StudioMcpServer[]>;
  reconcileMcp(input: { binding: StudioBinding; mutationId: string; serverKey: string; enabled: boolean; secretReferenceId: string; toolKeys: string[] }): Promise<StudioMutationReceipt>;
};

const safeId = /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,199}$/;
const safeModel = /^[A-Za-z0-9][A-Za-z0-9_.:/-]{0,239}$/;
const hex64 = /^[a-f0-9]{64}$/;
const commonKeys = ["contractVersion", "projectId", "runtimeId", "runtimeAssignmentId", "profileId"] as const;
const capabilityNames = ["models", "profileFiles", "skills", "skillLifecycle", "mcp"] as const;
type CapabilityName = (typeof capabilityNames)[number];
function object(value: unknown, code: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(code); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, keys: readonly string[], code: string) { const actual = Object.keys(value).sort(), expected = [...keys].sort(); if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) throw new Error(code); }
function string(value: unknown, max: number, code: string, pattern?: RegExp) { if (typeof value !== "string" || !value || value.length > max || (pattern && !pattern.test(value))) throw new Error(code); return value; }
function integer(value: unknown, code: string) { if (!Number.isInteger(value) || Number(value) < 0 || Number(value) > 1_000_000_000_000_000) throw new Error(code); return Number(value); }
function assertCommon(value: Record<string, unknown>, binding: StudioBinding) { if (value.contractVersion !== EMPLOYEE_STUDIO_CONTRACT || value.projectId !== binding.projectId || value.runtimeId !== binding.runtimeId || value.runtimeAssignmentId !== binding.runtimeAssignmentId || value.profileId !== binding.profileId) throw new Error("EMPLOYEE_STUDIO_BINDING_MISMATCH"); }
function responseKeys(...extra: string[]) { return [...commonKeys, ...extra]; }
function digestOf(value: string) { return createHash("sha256").update(value).digest("hex"); }
function providerFor(value: string) { return value.includes("/") ? value.split("/", 1)[0] : "hermes"; }
export function isAllowedProfileFileKey(value: string): value is (typeof STUDIO_PROFILE_KEYS)[number] { return (STUDIO_PROFILE_KEYS as readonly string[]).includes(value); }
export function validateStudioBinding(binding: StudioBinding) { if ([binding.projectId, binding.runtimeId, binding.runtimeAssignmentId, binding.profileId, binding.actorId].some((value) => !safeId.test(value))) throw new Error("EMPLOYEE_STUDIO_INVALID_BINDING"); return binding; }

export function parseStudioCapabilities(value: unknown, binding: StudioBinding): StudioCapabilities {
  const row = object(value, "EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); exact(row, responseKeys("capabilities"), "EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); assertCommon(row, binding);
  if (!Array.isArray(row.capabilities) || row.capabilities.length !== 5) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); const states = new Map<CapabilityName, SetupState>();
  for (const item of row.capabilities) { const capability = object(item, "EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); exact(capability, ["name", "state"], "EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); if (!capabilityNames.includes(capability.name as CapabilityName) || !["READY", "SETUP_REQUIRED", "UNAVAILABLE"].includes(String(capability.state)) || states.has(capability.name as CapabilityName)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); states.set(capability.name as CapabilityName, capability.state as SetupState); }
  const get = (name: CapabilityName): StudioCapabilityState => { const reason = states.get(name); if (!reason) throw new Error("EMPLOYEE_STUDIO_MALFORMED_CAPABILITIES"); return { available: reason === "READY", reason }; };
  return { contractVersion: EMPLOYEE_STUDIO_CONTRACT, binding, model: get("models"), profileFiles: get("profileFiles"), skills: get("skills"), skillLifecycle: get("skillLifecycle"), mcp: get("mcp"), observedAt: new Date().toISOString() };
}

type ParsedCatalog = { models: Array<{ id: string; state: SetupState }>; revision: number; expiresAt: number; expired: boolean };
export function parseStudioCatalog(value: unknown, binding: StudioBinding, secret: string): ParsedCatalog {
  const row = object(value, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); exact(row, responseKeys("catalog", "signature"), "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); assertCommon(row, binding); const signature = string(row.signature, 64, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG", hex64);
  const unsigned = { contractVersion: row.contractVersion, projectId: row.projectId, runtimeId: row.runtimeId, runtimeAssignmentId: row.runtimeAssignmentId, profileId: row.profileId, catalog: row.catalog }; const expected = createHmac("sha256", secret).update(JSON.stringify(unsigned)).digest("hex"); if (!secret || !timingSafeEqual(Buffer.from(signature, "hex"), Buffer.from(expected, "hex"))) throw new Error("EMPLOYEE_STUDIO_CATALOG_SIGNATURE_INVALID");
  const catalog = object(row.catalog, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); exact(catalog, ["models", "revision", "expiresAt", "expired"], "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); if (!Array.isArray(catalog.models) || catalog.models.length > 100 || typeof catalog.expired !== "boolean") throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); const seen = new Set<string>();
  const models = catalog.models.map((item) => { const model = object(item, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); exact(model, ["id", "state"], "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); const id = string(model.id, 240, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG", safeModel), state = string(model.state, 32, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG", /^(READY|SETUP_REQUIRED|UNAVAILABLE)$/) as SetupState; if (seen.has(id)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"); seen.add(id); return { id, state }; });
  return { models, revision: integer(catalog.revision, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"), expiresAt: integer(catalog.expiresAt, "EMPLOYEE_STUDIO_MALFORMED_MODEL_CATALOG"), expired: catalog.expired };
}
function parseModelRead(value: unknown, binding: StudioBinding) { const row = object(value, "EMPLOYEE_STUDIO_MALFORMED_MODEL"); exact(row, responseKeys("model"), "EMPLOYEE_STUDIO_MALFORMED_MODEL"); assertCommon(row, binding); const model = object(row.model, "EMPLOYEE_STUDIO_MALFORMED_MODEL"); exact(model, ["id", "revision"], "EMPLOYEE_STUDIO_MALFORMED_MODEL"); return { id: string(model.id, 240, "EMPLOYEE_STUDIO_MALFORMED_MODEL", safeModel), revision: integer(model.revision, "EMPLOYEE_STUDIO_MALFORMED_MODEL") }; }
export function parseStudioProfileFile(value: unknown, binding: StudioBinding): StudioProfileFile { const row = object(value, "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); exact(row, responseKeys("file"), "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); assertCommon(row, binding); const file = object(row.file, "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); exact(file, ["key", "content", "digest", "revision"], "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); const logicalKey = string(file.key, 32, "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"), content = typeof file.content === "string" ? file.content : "", digest = string(file.digest, 64, "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE", hex64); if (!isAllowedProfileFileKey(logicalKey) || content.includes("\0") || Buffer.byteLength(content, "utf8") > 65_536 || digestOf(content) !== digest) throw new Error("EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"); return { logicalKey, displayName: logicalKey[0].toUpperCase() + logicalKey.slice(1), editable: true, version: integer(file.revision, "EMPLOYEE_STUDIO_MALFORMED_PROFILE_FILE"), digest, byteLength: Buffer.byteLength(content, "utf8"), content }; }

export function parseStudioReceipt(value: unknown, binding: StudioBinding, mutationId: string): StudioMutationReceipt {
  const row = object(value, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); exact(row, responseKeys("receipt"), "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); assertCommon(row, binding); const receipt = object(row.receipt, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); let status: "APPLIED" | "ROLLED_BACK" = "APPLIED"; let observed: Record<string, unknown>;
  if (receipt.kind === "MODEL_UPDATED") { exact(receipt, ["kind", "modelId", "previousModelId", "revision", "confirmed"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); if (receipt.confirmed !== true) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); const id = string(receipt.modelId, 240, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT", safeModel); observed = { provider: providerFor(id), modelId: id, revision: integer(receipt.revision, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT") }; }
  else if (receipt.kind === "MODEL_ROLLBACK") { exact(receipt, ["kind", "requestedModelId", "restoredModelId", "revision", "confirmed"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); if (receipt.confirmed !== false) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); const id = string(receipt.restoredModelId, 240, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT", safeModel); status = "ROLLED_BACK"; observed = { provider: providerFor(id), modelId: id, revision: integer(receipt.revision, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT") }; }
  else if (receipt.kind === "PROFILE_FILE_UPDATED") { exact(receipt, ["kind", "profileId", "key", "revision", "digest", "previousDigest"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); const key = string(receipt.key, 32, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); if (receipt.profileId !== binding.profileId || !isAllowedProfileFileKey(key)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); observed = { logicalKey: key, version: integer(receipt.revision, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"), digest: string(receipt.digest, 64, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT", hex64) }; }
  else if (receipt.kind === "PROFILE_FILE_RESTORED") { exact(receipt, ["kind", "profileId", "key", "restoredFromRevision", "revision", "digest"], "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); const key = string(receipt.key, 32, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); if (receipt.profileId !== binding.profileId || !isAllowedProfileFileKey(key)) throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); observed = { logicalKey: key, version: integer(receipt.revision, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT"), digest: string(receipt.digest, 64, "EMPLOYEE_STUDIO_MALFORMED_RECEIPT", hex64) }; }
  else throw new Error("EMPLOYEE_STUDIO_MALFORMED_RECEIPT"); return { contractVersion: EMPLOYEE_STUDIO_CONTRACT, binding, mutationId, receiptId: digestOf(JSON.stringify(row)), status, observed, observedFingerprint: digestOf(JSON.stringify(receipt)), completedAt: new Date().toISOString() };
}
function parseSkills(value: unknown, binding: StudioBinding): StudioSkill[] { const row = object(value, "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); exact(row, responseKeys("inventory"), "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); assertCommon(row, binding); const inventory = object(row.inventory, "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); exact(inventory, ["skills", "revision"], "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); integer(inventory.revision, "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); if (!Array.isArray(inventory.skills) || inventory.skills.length > 100) throw new Error("EMPLOYEE_STUDIO_MALFORMED_SKILLS"); return inventory.skills.map((item) => { const skill = object(item, "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); exact(skill, ["id", "state", "version"], "EMPLOYEE_STUDIO_MALFORMED_SKILLS"); const key = string(skill.id, 120, "EMPLOYEE_STUDIO_MALFORMED_SKILLS", safeId), state = string(skill.state, 24, "EMPLOYEE_STUDIO_MALFORMED_SKILLS", /^(AVAILABLE|ENABLED|DISABLED|UNAVAILABLE)$/); return { key, name: key, version: string(skill.version, 80, "EMPLOYEE_STUDIO_MALFORMED_SKILLS"), installed: state !== "UNAVAILABLE", enabled: state === "ENABLED", readable: state !== "UNAVAILABLE", digest: null, content: null }; }); }

function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => [key, canonical(item)])); if (typeof value === "number" && !Number.isFinite(value)) throw new Error("EMPLOYEE_STUDIO_INVALID_ENVELOPE"); return value; }
export function signStudioEnvelope(envelope: Record<string, unknown>, secret: string) { return createHmac("sha256", secret).update(JSON.stringify(canonical(envelope))).digest("hex"); }
const baseUrl = () => process.env.ROGEROS_EMPLOYEE_STUDIO_ADAPTER_URL?.replace(/\/$/, ""); const token = () => process.env.ROGEROS_EMPLOYEE_STUDIO_ADAPTER_TOKEN; const envelopeSecret = () => process.env.ROGEROS_EMPLOYEE_STUDIO_HMAC_SECRET; const catalogSecret = () => process.env.ROGEROS_EMPLOYEE_STUDIO_CATALOG_HMAC_SECRET;
export function employeeStudioAdapterConfigured() { return process.env.ROGEROS_EMPLOYEE_STUDIO_ENABLED === "true" && Boolean(baseUrl() && token() && envelopeSecret() && catalogSecret()); }
async function request(path: string, operation: string, binding: StudioBinding, payload: Record<string, unknown>, options: { idempotencyKey?: string; expectedRevision?: number | null; expectedFingerprint?: string | null } = {}) { validateStudioBinding(binding); const base = baseUrl(), auth = token(), secret = envelopeSecret(); if (!employeeStudioAdapterConfigured() || !base || !auth || !secret) throw new Error("EMPLOYEE_STUDIO_NOT_CONFIGURED"); const unsigned = { contractVersion: EMPLOYEE_STUDIO_CONTRACT, projectId: binding.projectId, runtimeId: binding.runtimeId, runtimeAssignmentId: binding.runtimeAssignmentId, profileId: binding.profileId, actorId: binding.actorId, timestamp: Date.now(), nonce: randomBytes(32).toString("base64url"), idempotencyKey: options.idempotencyKey || randomUUID(), expectedRevision: options.expectedRevision ?? null, expectedFingerprint: options.expectedFingerprint ?? null, operation, payload }; const response = await fetch(`${base}${path}`, { method: "POST", cache: "no-store", redirect: "error", headers: { Authorization: `Bearer ${auth}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...unsigned, signature: signStudioEnvelope(unsigned, secret) }) }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: unknown } | null; const code = typeof body?.error === "string" && /^[A-Z0-9_]{1,120}$/.test(body.error) ? body.error : `HTTP_${response.status}`; throw new Error(`EMPLOYEE_STUDIO_${code}`); } return response.json() as Promise<unknown>; }
export const employeeStudioAdapter: EmployeeStudioAdapter = {
  capabilities: async (binding) => parseStudioCapabilities(await request("/v1/capabilities", "CAPABILITIES", binding, {}), binding),
  modelCatalog: async (binding) => { const [catalogValue, modelValue] = await Promise.all([request("/v1/models/catalog", "MODEL_CATALOG", binding, {}), request("/v1/models/read", "MODEL_READ", binding, {})]); const catalog = parseStudioCatalog(catalogValue, binding, catalogSecret() || ""), current = parseModelRead(modelValue, binding); if (catalog.expired) throw new Error("EMPLOYEE_STUDIO_STALE_MODEL_CATALOG"); const expiry = catalog.expiresAt < 10_000_000_000 ? catalog.expiresAt * 1000 : catalog.expiresAt; return { contractVersion: EMPLOYEE_STUDIO_CONTRACT, binding, revision: String(catalog.revision), expiresAt: new Date(expiry).toISOString(), current: { provider: providerFor(current.id), modelId: current.id, revision: current.revision }, models: catalog.models.map((model) => ({ provider: providerFor(model.id), modelId: model.id, displayName: model.id, setupState: model.state })) }; },
  changeModel: async (input) => parseStudioReceipt(await request("/v1/models/set", "MODEL_SET", input.binding, { modelId: input.modelId, observedModelId: input.observedModelId }, { idempotencyKey: input.mutationId, expectedRevision: input.expectedRevision, expectedFingerprint: input.expectedFingerprint }), input.binding, input.mutationId),
  rollbackModel: async (input) => ({ ...parseStudioReceipt(await request("/v1/models/set", "MODEL_SET", input.binding, { modelId: input.modelId, observedModelId: input.observedModelId }, { idempotencyKey: `${input.mutationId}:rollback`, expectedRevision: input.expectedRevision }), input.binding, input.mutationId), status: "ROLLED_BACK" as const }),
  listProfileFiles: async (binding) => Promise.all(STUDIO_PROFILE_KEYS.map((key) => employeeStudioAdapter.readProfileFile(binding, key).then((file) => ({ logicalKey: file.logicalKey, displayName: file.displayName, editable: file.editable, version: file.version, digest: file.digest, byteLength: file.byteLength })))),
  readProfileFile: async (binding, logicalKey) => { if (!isAllowedProfileFileKey(logicalKey)) throw new Error("EMPLOYEE_STUDIO_FILE_NOT_ALLOWED"); return parseStudioProfileFile(await request("/v1/profile-files/read", "PROFILE_FILE_READ", binding, { key: logicalKey }), binding); },
  writeProfileFile: async (input) => parseStudioReceipt(await request("/v1/profile-files/update", "PROFILE_FILE_UPDATE", input.binding, { key: input.logicalKey, content: input.content }, { idempotencyKey: input.mutationId, expectedRevision: input.expectedVersion, expectedFingerprint: input.expectedDigest }), input.binding, input.mutationId),
  restoreProfileFile: async (input) => parseStudioReceipt(await request("/v1/profile-files/restore", "PROFILE_FILE_RESTORE", input.binding, { key: input.logicalKey, backupRevision: input.restoreVersion }, { idempotencyKey: input.mutationId, expectedRevision: input.expectedVersion, expectedFingerprint: input.expectedDigest }), input.binding, input.mutationId),
  listSkills: async (binding) => parseSkills(await request("/v1/skills/inventory", "SKILL_INVENTORY", binding, {}), binding),
  listMcpServers: async () => [],
  reconcileMcp: async () => { throw new Error("EMPLOYEE_STUDIO_MCP_UNAVAILABLE"); },
};
