import { NextResponse } from 'next/server'
import { TaskActivityType, TaskPriority, TaskStatus } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { projectScopeErrorResponse, requireProjectContextForBody, requireProjectContextForRequest } from '@/lib/project-scope'
import { taskErrorResponse } from '@/lib/tasks'

export async function GET(request: Request) { try { const context = await requireProjectContextForRequest(request); const tasks = await prisma.task.findMany({ where: { projectId: context.project.id }, include: {
  assignments: { include: { projectMember: { include: { organizationMember: { include: { user: { select: { name: true, email: true } } } } } }, employeeProjectAssignment: { include: { employee: { select: { name: true } } } } } },
  subtasks: { select: { id: true, status: true } }, relatedThread: { select: { id: true, title: true } },
}, orderBy: { updatedAt: 'desc' } }); return NextResponse.json({ tasks }) } catch (e) { try { return projectScopeErrorResponse(e) } catch (x) { return taskErrorResponse(x) } } }
export async function POST(request: Request) { try { const body = await request.json() as Record<string, unknown>; const context = await requireProjectContextForBody(body); const title = typeof body.title === 'string' ? body.title.trim().slice(0, 200) : ''; if (!title) return NextResponse.json({ error: 'A title is required' }, { status: 400 }); const parentTaskId = typeof body.parentTaskId === 'string' ? body.parentTaskId : null; const relatedThreadId = typeof body.relatedThreadId === 'string' ? body.relatedThreadId : null; const projectMemberId = typeof body.projectMemberId === 'string' ? body.projectMemberId : null; if (parentTaskId && !await prisma.task.findFirst({ where: { id: parentTaskId, projectId: context.project.id } })) return NextResponse.json({ error: 'Not found' }, { status: 404 }); if (relatedThreadId && !await prisma.thread.findFirst({ where: { id: relatedThreadId, projectId: context.project.id, conversation: { participants: { some: { userId: context.user.id } } } } })) return NextResponse.json({ error: 'Not found' }, { status: 404 }); if (projectMemberId && !await prisma.projectMember.findFirst({ where: { id: projectMemberId, projectId: context.project.id } })) return NextResponse.json({ error: 'Not found' }, { status: 404 }); const status = Object.values(TaskStatus).includes(body.status as TaskStatus) ? body.status as TaskStatus : 'TODO'; const priority = Object.values(TaskPriority).includes(body.priority as TaskPriority) ? body.priority as TaskPriority : 'MEDIUM'; const dueAt = typeof body.dueAt === 'string' && body.dueAt ? new Date(body.dueAt) : null; const task = await prisma.task.create({ data: { projectId: context.project.id, title, description: typeof body.description === 'string' ? body.description.trim().slice(0, 10000) || null : null, status, priority, dueAt, parentTaskId, relatedThreadId, createdById: context.user.id, assignments: projectMemberId ? { create: { projectMemberId } } : undefined, activities: { create: { actorUserId: context.user.id, type: TaskActivityType.CREATED, detail: 'Task created' } } } }); return NextResponse.json({ task }, { status: 201 }) } catch (e) { try { return projectScopeErrorResponse(e) } catch (x) { return taskErrorResponse(x) } } }
