import test from 'node:test'
import assert from 'node:assert/strict'
import { PrismaClient, Prisma } from '@prisma/client'
import { createApprovalRequestFromAuthorization, decideApprovalRequest } from '../src/lib/approvals'
import { resolveToolAuthorization } from '../src/lib/tool-permissions'

const prisma = new PrismaClient(); const suffix = `m10-${Date.now()}`
test('M10 approvals remain project-scoped, policy-aware, and race-safe', async t => {
 const org=await prisma.organization.create({data:{name:'M10 Test',slug:suffix}}); const users=await Promise.all(['owner','admin','approver','operator','viewer'].map(role=>prisma.user.create({data:{email:`${suffix}-${role}@example.invalid`}}))); const members=await Promise.all(users.map((u,i)=>prisma.organizationMember.create({data:{userId:u.id,organizationId:org.id,role:i===0?'OWNER':'VIEWER'}}))); const [v,b]=await Promise.all(['v','b'].map(name=>prisma.project.create({data:{organizationId:org.id,name,slug:`${name}-${suffix}`}}))); const projectMembers=await Promise.all(members.map((m,i)=>prisma.projectMember.create({data:{projectId:v.id,organizationId:org.id,organizationMemberId:m.id,role:['OWNER','ADMIN','APPROVER','OPERATOR','VIEWER'][i] as 'OWNER'}}))); const emp=await prisma.employee.create({data:{name:'M10 employee',role:'Test'}}); const [va,ba]=await Promise.all([prisma.employeeProjectAssignment.create({data:{projectId:v.id,employeeId:emp.id}}),prisma.employeeProjectAssignment.create({data:{projectId:b.id,employeeId:emp.id}})]); const tool=await prisma.toolDefinition.create({data:{key:suffix,name:'M10 tool',category:'TEST'}}); const [vt,bt]=await Promise.all([prisma.projectTool.create({data:{projectId:v.id,toolDefinitionId:tool.id}}),prisma.projectTool.create({data:{projectId:b.id,toolDefinitionId:tool.id}})]); await prisma.employeeToolPermission.create({data:{projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:vt.id,level:'EXECUTE_WITH_APPROVAL'}}); t.after(async()=>{await prisma.organization.delete({where:{id:org.id}});await prisma.user.deleteMany({where:{id:{in:users.map(u=>u.id)}}});await prisma.employee.delete({where:{id:emp.id}});await prisma.toolDefinition.delete({where:{id:tool.id}});await prisma.$disconnect()});
 const request=await createApprovalRequestFromAuthorization({projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:vt.id,action:'execute',summary:'Safe test action',actionContext:{test:true}}); assert.equal(request.status,'PENDING'); const events=await prisma.auditEvent.findMany({where:{projectId:v.id,approvalRequestId:request.id}}); assert.equal(events.some(e=>e.eventType==='approval.requested'),true); assert.equal(events.some(e=>e.eventType==='authorization.require_approval'),true); await assert.rejects(createApprovalRequestFromAuthorization({projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:bt.id,action:'execute',summary:'cross',actionContext:{}})); await assert.rejects(createApprovalRequestFromAuthorization({projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:vt.id,action:'read',summary:'allow no approval',actionContext:{}}));
 await prisma.employeeToolPermission.updateMany({where:{projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:vt.id},data:{level:'FULL_EXECUTE'}}); await prisma.policy.create({data:{projectId:v.id,title:'Require review',description:'Test policy',status:'ACTIVE',enforcement:'REQUIRE_APPROVAL',rule:{action:'execute'}}}); assert.equal(await resolveToolAuthorization({projectId:v.id,assignmentId:va.id,projectToolId:vt.id,action:'execute'}),'REQUIRE_APPROVAL'); const policyRequest=await createApprovalRequestFromAuthorization({projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:vt.id,action:'execute',summary:'Policy constrained action',actionContext:{test:true}}); assert.equal(policyRequest.status,'PENDING'); await prisma.policy.create({data:{projectId:v.id,title:'Block',description:'Test block',status:'ACTIVE',enforcement:'BLOCK',rule:{action:'execute'}}}); assert.equal(await resolveToolAuthorization({projectId:v.id,assignmentId:va.id,projectToolId:vt.id,action:'execute'}),'DENY'); await assert.rejects(createApprovalRequestFromAuthorization({projectId:v.id,employeeProjectAssignmentId:va.id,projectToolId:vt.id,action:'execute',summary:'Blocked cannot bypass',actionContext:{test:true}}));
 await assert.rejects(decideApprovalRequest({projectId:v.id,approvalId:request.id,approverProjectMemberId:projectMembers[3].id,outcome:'APPROVED'})); await assert.rejects(decideApprovalRequest({projectId:v.id,approvalId:request.id,approverProjectMemberId:projectMembers[4].id,outcome:'APPROVED'})); const results=await Promise.allSettled([decideApprovalRequest({projectId:v.id,approvalId:request.id,approverProjectMemberId:projectMembers[0].id,outcome:'APPROVED'}),decideApprovalRequest({projectId:v.id,approvalId:request.id,approverProjectMemberId:projectMembers[1].id,outcome:'REJECTED'})]); assert.equal(results.filter(r=>r.status==='fulfilled').length,1); const final=await prisma.approvalRequest.findUniqueOrThrow({where:{id:request.id}}); assert.ok(['APPROVED','REJECTED'].includes(final.status)); assert.equal(await prisma.approvalRequest.findFirst({where:{id:request.id,projectId:b.id}}),null); await assert.rejects(prisma.approvalRequest.create({data:{projectId:v.id,requestedByEmployeeAssignmentId:ba.id,projectToolId:vt.id,actionKey:'execute',summary:'bad',actionContext:{},authorizationSnapshot:{},policySnapshot:{}}}),(e:unknown)=>e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2003');
})
