CREATE TYPE "HermesRuntimeStatus" AS ENUM ('ACTIVE', 'PAUSED', 'ARCHIVED');
CREATE TYPE "HermesExecutionStatus" AS ENUM ('QUEUED', 'DISPATCHING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED');
ALTER TYPE "TaskActivityType" ADD VALUE 'RUNTIME_QUEUED';
ALTER TYPE "TaskActivityType" ADD VALUE 'RUNTIME_STARTED';
ALTER TYPE "TaskActivityType" ADD VALUE 'RUNTIME_SUCCEEDED';
ALTER TYPE "TaskActivityType" ADD VALUE 'RUNTIME_FAILED';
CREATE TABLE "HermesRuntime" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "name" TEXT NOT NULL, "status" "HermesRuntimeStatus" NOT NULL DEFAULT 'ACTIVE', "endpoint" TEXT, "profileKey" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HermesRuntime_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HermesRuntimeAssignment" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "runtimeId" TEXT NOT NULL, "employeeProjectAssignmentId" TEXT, "profileKey" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HermesRuntimeAssignment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HermesExecution" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "runtimeId" TEXT NOT NULL, "runtimeAssignmentId" TEXT NOT NULL, "status" "HermesExecutionStatus" NOT NULL DEFAULT 'QUEUED', "prompt" TEXT NOT NULL, "resultText" TEXT, "errorMessage" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HermesExecution_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "HermesRuntime_key_key" ON "HermesRuntime"("key");
CREATE INDEX "HermesRuntimeAssignment_projectId_active_idx" ON "HermesRuntimeAssignment"("projectId", "active");
CREATE UNIQUE INDEX "HermesRuntimeAssignment_projectId_runtimeId_key" ON "HermesRuntimeAssignment"("projectId", "runtimeId");
CREATE UNIQUE INDEX "HermesRuntimeAssignment_id_projectId_key" ON "HermesRuntimeAssignment"("id", "projectId");
CREATE INDEX "HermesExecution_projectId_status_createdAt_idx" ON "HermesExecution"("projectId", "status", "createdAt");
CREATE UNIQUE INDEX "HermesExecution_taskId_status_key" ON "HermesExecution"("taskId", "status");
ALTER TABLE "HermesRuntimeAssignment" ADD CONSTRAINT "HermesRuntimeAssignment_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HermesRuntimeAssignment" ADD CONSTRAINT "HermesRuntimeAssignment_runtimeId_fkey" FOREIGN KEY ("runtimeId") REFERENCES "HermesRuntime"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HermesRuntimeAssignment" ADD CONSTRAINT "HermesRuntimeAssignment_employeeProjectAssignmentId_projectId_fkey" FOREIGN KEY ("employeeProjectAssignmentId", "projectId") REFERENCES "EmployeeProjectAssignment"("id", "projectId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HermesExecution" ADD CONSTRAINT "HermesExecution_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HermesExecution" ADD CONSTRAINT "HermesExecution_taskId_projectId_fkey" FOREIGN KEY ("taskId", "projectId") REFERENCES "Task"("id", "projectId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HermesExecution" ADD CONSTRAINT "HermesExecution_runtimeId_fkey" FOREIGN KEY ("runtimeId") REFERENCES "HermesRuntime"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HermesExecution" ADD CONSTRAINT "HermesExecution_runtimeAssignmentId_projectId_fkey" FOREIGN KEY ("runtimeAssignmentId", "projectId") REFERENCES "HermesRuntimeAssignment"("id", "projectId") ON DELETE RESTRICT ON UPDATE CASCADE;
