import { NextResponse } from 'next/server'
import { PermissionLevel } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { projectScopeErrorResponse, requireProjectContextForBody, requireProjectContextForRequest } from '@/lib/project-scope'
import { canManageToolPermissions } from '@/lib/tool-permissions'
import { recordAuditEvent } from '@/lib/audit'
import { AuditActorType } from '@prisma/client'

export async function GET(request: Request) { try { const context = await requireProjectContextForRequest(request); return NextResponse.json({ permissions: await prisma.employeeToolPermission.findMany({ where: { projectId: context.project.id }, include: { employeeAssignment: { include: { employee: true } }, projectTool: { include: { tool: true } } } }) }) } catch (error) { return projectScopeErrorResponse(error) } }
export async function PUT(request: Request) { try { const body = await request.json() as Record<string, unknown>; const context = await requireProjectContextForBody(body); if (!canManageToolPermissions(context.project.role)) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const assignmentId = typeof body.employeeProjectAssignmentId === 'string' ? body.employeeProjectAssignmentId : ''; const projectToolId = typeof body.projectToolId === 'string' ? body.projectToolId : ''; const level = typeof body.level === 'string' && Object.values(PermissionLevel).includes(body.level as PermissionLevel) ? body.level as PermissionLevel : null; if (!assignmentId || !projectToolId || !level) return NextResponse.json({ error: 'Invalid permission input' }, { status: 400 }); const [assignment, tool, prior] = await Promise.all([prisma.employeeProjectAssignment.findFirst({ where: { id: assignmentId, projectId: context.project.id }, select: { id: true } }), prisma.projectTool.findFirst({ where: { id: projectToolId, projectId: context.project.id }, select: { id: true } }), prisma.employeeToolPermission.findFirst({ where: { projectId: context.project.id, employeeProjectAssignmentId: assignmentId, projectToolId, capabilityKey: '*' }, select: { id: true, level: true } })]); if (!assignment || !tool) return NextResponse.json({ error: 'Not found' }, { status: 404 }); const permission = await prisma.employeeToolPermission.upsert({ where: { employeeProjectAssignmentId_projectToolId_capabilityKey: { employeeProjectAssignmentId: assignmentId, projectToolId, capabilityKey: '*' } }, create: { projectId: context.project.id, employeeProjectAssignmentId: assignmentId, projectToolId, level, grantedById: context.user.id }, update: { level, grantedById: context.user.id } }); const member = await prisma.projectMember.findFirst({ where: { projectId: context.project.id, organizationMember: { userId: context.user.id } }, select: { id: true } }); if (member) await recordAuditEvent({ projectId: context.project.id, eventType: level === 'NO_ACCESS' ? 'employee_tool_permission.revoked' : prior ? 'employee_tool_permission.updated' : 'employee_tool_permission.created', actor: { type: AuditActorType.HUMAN, projectMemberId: member.id }, targetType: 'EmployeeToolPermission', targetId: permission.id, projectToolId, summary: `Tool permission set to ${level}`, metadata: { assignmentId, level, previousLevel: prior?.level ?? null } }); return NextResponse.json({ permission }) } catch (error) { return projectScopeErrorResponse(error) } }
