import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { projectScopeErrorResponse, requireProjectContextForBody, requireProjectContextForRequest } from '@/lib/project-scope'
import { canManageToolPermissions, ensureBuiltInToolCatalog } from '@/lib/tool-permissions'
import { recordAuditEvent } from '@/lib/audit'
import { AuditActorType } from '@prisma/client'

export async function GET(request: Request) { try { const context = await requireProjectContextForRequest(request); await ensureBuiltInToolCatalog(); const [tools,catalog]=await Promise.all([prisma.projectTool.findMany({ where: { projectId: context.project.id }, include: { tool: { include: { capabilities: true } }, _count: { select: { permissions: true } } }, orderBy: { tool: { name: 'asc' } } }),prisma.toolDefinition.findMany({where:{builtIn:true},orderBy:{name:'asc'}})]); return NextResponse.json({ tools,catalog }) } catch (error) { return projectScopeErrorResponse(error) } }
export async function POST(request: Request) { try { const body = await request.json() as Record<string, unknown>; const context = await requireProjectContextForBody(body); if (!canManageToolPermissions(context.project.role)) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const toolDefinitionId = typeof body.toolDefinitionId === 'string' ? body.toolDefinitionId : ''; const tool = await prisma.toolDefinition.findUnique({ where: { id: toolDefinitionId }, select: { id: true, builtIn: true, name: true } }); if (!tool?.builtIn) return NextResponse.json({ error: 'Unknown built-in tool' }, { status: 400 }); const existing = await prisma.projectTool.findUnique({ where: { projectId_toolDefinitionId: { projectId: context.project.id, toolDefinitionId: tool.id } }, select: { id: true } }); const projectTool = await prisma.projectTool.upsert({ where: { projectId_toolDefinitionId: { projectId: context.project.id, toolDefinitionId: tool.id } }, create: { projectId: context.project.id, toolDefinitionId: tool.id }, update: {} }); if (!existing) { const member = await prisma.projectMember.findFirst({ where: { projectId: context.project.id, organizationMember: { userId: context.user.id } }, select: { id: true } }); if (member) await recordAuditEvent({ projectId: context.project.id, eventType: 'project_tool.installed', actor: { type: AuditActorType.HUMAN, projectMemberId: member.id }, targetType: 'ProjectTool', targetId: projectTool.id, projectToolId: projectTool.id, summary: `Installed ${tool.name}`, metadata: { toolDefinitionId: tool.id } }) } return NextResponse.json({ projectTool }, { status: 201 }) } catch (error) { return projectScopeErrorResponse(error) } }
