'use client'

import { useState } from 'react'
import { Activity, Check, Clock3, ShieldCheck, X } from 'lucide-react'
import { Avatar, EmptyState, Metric, PageHeader, StatusPill, friendlyLabel } from '@/components/rogeros-ui'

type Approval = { id:string; status:string; summary:string; actionKey:string; capabilityKey:string; permissionLevel:string|null; requestedAt:string|Date; expiresAt:string|Date|null; requestedByEmployee?:{employee:{name:string}}|null; projectTool:{tool:{name:string}}; task?:{title:string}|null; auditEvents:Array<{id:string;eventType:string;summary:string;createdAt:string|Date}> }
type Event = { id:string; eventType:string; summary:string; createdAt:string|Date; actorProjectMember?:{organizationMember:{user:{name:string|null,email:string|null}}}|null; actorEmployeeAssignment?:{employee:{name:string}}|null }

export function ApprovalWorkspace({ project, canDecide, initialApprovals, initialEvents }: { project:{id:string;name:string}; canDecide:boolean; initialApprovals:Approval[]; initialEvents:Event[] }) {
  const [approvals,setApprovals]=useState(initialApprovals); const [events,setEvents]=useState(initialEvents); const [tab,setTab]=useState<'approvals'|'audit'>('approvals'); const [filter,setFilter]=useState('PENDING'); const [busy,setBusy]=useState<string|null>(null); const [notes,setNotes]=useState<Record<string,string>>({}); const [error,setError]=useState('')
  const decide = async (id:string,outcome:'APPROVED'|'REJECTED') => { setBusy(id); setError(''); try { const response=await fetch(`/api/approvals/${id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,outcome,note:notes[id]||''})}); if(!response.ok)throw new Error(); const data=await response.json(); setApprovals(items=>items.map(item=>item.id===id?{...item,...data.approval}:item)); setEvents(items=>[{id:`local-${id}-${outcome}`,eventType:outcome==='APPROVED'?'approval.approved':'approval.rejected',summary:`Request ${outcome.toLowerCase()}`,createdAt:new Date().toISOString()},...items]); setNotes(current=>({...current,[id]:''})) } catch { setError('The decision could not be saved. Nothing was executed.'); } finally { setBusy(null) } }
  const visible=filter==='ALL'?approvals:approvals.filter(item=>item.status===filter); const pending=approvals.filter(item=>item.status==='PENDING').length; const approved=approvals.filter(item=>item.status==='APPROVED').length; const rejected=approvals.filter(item=>item.status==='REJECTED').length

  return <div className="hq-rise">
    <PageHeader eyebrow={`${project.name} · Control`} title="Approvals" description="Review sensitive actions before they happen, with a clear record of every decision." />
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Waiting for review" value={pending} tone={pending?'warn':'good'}/><Metric label="Approved" value={approved}/><Metric label="Declined" value={rejected}/></div>
    {error&&<div role="alert" className="mt-4 rounded-xl border border-[rgba(235,130,122,.25)] bg-[rgba(235,130,122,.08)] px-4 py-3 text-[11px] text-[var(--ros-bad)]">{error}</div>}
    <div className="mt-7 flex gap-1 border-b border-[var(--ros-line)]"><button onClick={()=>setTab('approvals')} className={`border-b-2 px-3 py-2.5 text-[11px] font-medium ${tab==='approvals'?'border-[var(--ros-accent)] text-[var(--ros-text)]':'border-transparent text-[var(--ros-faint)]'}`}>Review queue</button><button onClick={()=>setTab('audit')} className={`border-b-2 px-3 py-2.5 text-[11px] font-medium ${tab==='audit'?'border-[var(--ros-accent)] text-[var(--ros-text)]':'border-transparent text-[var(--ros-faint)]'}`}>Activity record</button></div>
    {tab==='approvals'?<><div className="mt-5 flex flex-wrap gap-2">{['PENDING','APPROVED','REJECTED','ALL'].map(value=><button key={value} onClick={()=>setFilter(value)} className={`rounded-full px-3 py-1.5 text-[9px] font-medium ${filter===value?'bg-white/[.09] text-[var(--ros-text)]':'text-[var(--ros-faint)] hover:bg-white/[.035]'}`}>{value==='PENDING'?'Waiting':value==='APPROVED'?'Approved':value==='REJECTED'?'Declined':'All'}</button>)}</div><div className="mt-4 space-y-3">{visible.length===0?<section className="panel"><EmptyState icon={<ShieldCheck/>} title={filter==='PENDING'?'Nothing needs your review':'No matching decisions'} description={filter==='PENDING'?'RogerOS will surface sensitive employee actions here before anything happens.':'Choose another filter to review past requests.'}/></section>:visible.map(item=><ApprovalCard key={item.id} item={item} canDecide={canDecide} busy={busy===item.id} note={notes[item.id]||''} setNote={value=>setNotes(current=>({...current,[item.id]:value}))} decide={outcome=>void decide(item.id,outcome)}/>)}</div></>:<div className="mt-5">{events.length===0?<section className="panel"><EmptyState icon={<Activity/>} title="No recorded activity yet" description="Important project decisions and controlled actions will appear here."/></section>:<div className="panel divide-y divide-[var(--ros-line)]">{events.map(event=>{const actor=event.actorProjectMember?.organizationMember.user.name||event.actorProjectMember?.organizationMember.user.email||event.actorEmployeeAssignment?.employee.name||'RogerOS'; return <article className="flex gap-3 px-4 py-3.5" key={event.id}><Avatar name={actor} size="sm"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[11px] font-medium">{friendlyLabel(event.eventType.replaceAll('.',' '))}</p><time className="text-[9px] text-[var(--ros-faint)]">{new Date(event.createdAt).toLocaleString()}</time></div><p className="mt-1 text-[10px] leading-4 text-[var(--ros-muted)]">{event.summary}</p><p className="mt-1 text-[9px] text-[var(--ros-faint)]">{actor}</p></div></article>})}</div>}</div>}
  </div>
}

function ApprovalCard({ item, canDecide, busy, note, setNote, decide }: { item:Approval; canDecide:boolean; busy:boolean; note:string; setNote:(value:string)=>void; decide:(outcome:'APPROVED'|'REJECTED')=>void }) { const employee=item.requestedByEmployee?.employee.name??'A team member'; return <article className="panel p-5"><div className="flex flex-wrap items-start gap-4"><Avatar name={employee} size="lg"/><div className="min-w-[220px] flex-1"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={item.status==='APPROVED'?'good':item.status==='REJECTED'?'bad':'warn'}>{item.status==='PENDING'?'Waiting':item.status==='REJECTED'?'Declined':friendlyLabel(item.status)}</StatusPill><span className="text-[9px] text-[var(--ros-faint)]">{new Date(item.requestedAt).toLocaleString()}</span></div><h2 className="mt-3 text-sm font-semibold leading-5">{item.summary}</h2><p className="mt-2 text-[10px] leading-5 text-[var(--ros-muted)]"><strong className="text-[var(--ros-text)]">{employee}</strong> wants to use <strong className="text-[var(--ros-text)]">{item.projectTool.tool.name}</strong> for {friendlyLabel(item.actionKey).toLowerCase()}.</p>{item.task&&<p className="mt-1 text-[10px] text-[var(--ros-faint)]">Related work: {item.task.title}</p>}<details className="mt-3"><summary className="cursor-pointer text-[9px] text-[var(--ros-faint)]">Review access details</summary><div className="mt-2 rounded-lg bg-black/[.1] p-3 text-[9px] leading-4 text-[var(--ros-faint)]"><p>Capability: {friendlyLabel(item.capabilityKey)}</p><p>Employee access: {item.permissionLevel?friendlyLabel(item.permissionLevel):'No explicit permission'}</p>{item.expiresAt&&<p>Review expires: {new Date(item.expiresAt).toLocaleString()}</p>}</div></details></div>{canDecide&&item.status==='PENDING'&&<div className="w-full rounded-xl bg-black/[.1] p-3 sm:w-56"><label className="text-[9px] text-[var(--ros-faint)]">Decision note (optional)</label><input aria-label="Decision note" value={note} onChange={event=>setNote(event.target.value)} className="mt-2 w-full px-3 py-2 text-[10px]" placeholder="Add context for the team"/><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>decide('APPROVED')} className="btn-primary inline-flex items-center justify-center gap-1.5 px-3 py-2 text-[10px]"><Check className="w-3"/> Approve</button><button disabled={busy} onClick={()=>decide('REJECTED')} className="btn-ghost inline-flex items-center justify-center gap-1.5 px-3 py-2 text-[10px]"><X className="w-3"/> Decline</button></div><p className="mt-2 flex items-center gap-1.5 text-[8px] text-[var(--ros-faint)]"><Clock3 className="w-3"/> Approval records the decision; execution stays governed.</p></div>}</div></article> }
