'use client'

import { FormEvent, type ReactNode, useCallback, useEffect, useState } from 'react'
import { BookOpen, Brain, FileText, Gavel, HardDrive, Lightbulb, Plus, Search } from 'lucide-react'

import { EmptyState, PageHeader, StatusPill } from '@/components/rogeros-ui'

type BrainItem = { id: string; title: string; content?: string; decision?: string }
type Data = { constitution: { title:string;content:string } | null; knowledge: BrainItem[]; decisions: BrainItem[]; memory: BrainItem[]; sources:number; driveSources:Array<{id:string;name:string;mimeType:string;status:string;webUrl:string|null}> }
type Tab = 'overview' | 'knowledge' | 'decisions' | 'memory' | 'sources'

export function BrainWorkspace({ project }: { project: { id:string;name:string } }) {
  const [data, setData] = useState<Data | null>(null); const [tab, setTab] = useState<Tab>('overview'); const [kind, setKind] = useState('knowledge'); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [query, setQuery] = useState(''); const [composing, setComposing] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { const response = await fetch(`/api/brain?projectId=${project.id}&q=${encodeURIComponent(query)}`); if (!response.ok) { setError('The Project Brain could not be loaded.'); return } setData(await response.json()) }, [project.id, query])
  useEffect(() => { const timer = setTimeout(() => { void load() }, 180); return () => clearTimeout(timer) }, [load])
  const save = async (event: FormEvent) => { event.preventDefault(); const response = await fetch('/api/brain', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ projectId:project.id, kind, title, content }) }); if (!response.ok) { setError('This knowledge could not be saved.'); return } setTitle(''); setContent(''); setComposing(false); await load() }
  const counts = { knowledge: data?.knowledge.length ?? 0, decisions: data?.decisions.length ?? 0, memory: data?.memory.length ?? 0, sources: data?.driveSources.length ?? 0 }

  return <div className="hq-rise">
    <PageHeader eyebrow={`${project.name} · Project intelligence`} title="Project Brain" description="The durable context your team and AI employees use to make better decisions." action={<button onClick={() => setComposing(value => !value)} className="btn-primary inline-flex items-center gap-2 px-3 py-2 text-xs"><Plus className="w-3.5"/> Add knowledge</button>} />
    {error && <div role="alert" className="mb-4 rounded-xl border border-[rgba(235,130,122,.25)] bg-[rgba(235,130,122,.08)] px-4 py-3 text-xs text-[var(--ros-bad)]">{error}</div>}
    <div className="flex gap-1 overflow-x-auto border-b border-[var(--ros-line)] pb-px">{([['overview','Overview'],['knowledge',`Knowledge ${counts.knowledge}`],['decisions',`Decisions ${counts.decisions}`],['memory',`Memory ${counts.memory}`],['sources',`Sources ${counts.sources}`]] as Array<[Tab,string]>).map(([value,label]) => <button key={value} onClick={() => setTab(value)} className={`whitespace-nowrap border-b-2 px-3 py-2.5 text-[11px] font-medium ${tab === value ? 'border-[var(--ros-accent)] text-[var(--ros-text)]' : 'border-transparent text-[var(--ros-faint)] hover:text-[var(--ros-muted)]'}`}>{label}</button>)}</div>
    <div className="relative mt-5"><Search className="pointer-events-none absolute left-3 top-2.5 w-3.5 text-[var(--ros-faint)]"/><input aria-label="Search Project Brain" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search the Project Brain…" className="w-full py-2.5 pl-9 pr-3 text-xs"/></div>
    {composing && <form onSubmit={save} className="panel mt-5 p-4"><div className="grid gap-3 sm:grid-cols-[180px_minmax(0,1fr)]"><div><label className="mb-1.5 block text-[10px] text-[var(--ros-muted)]">What is this?</label><select value={kind} onChange={event => setKind(event.target.value)} className="w-full px-3 py-2.5 text-xs"><option value="constitution">Constitution</option><option value="knowledge">Knowledge</option><option value="decisions">Decision</option><option value="memory">Memory</option></select></div><div><label className="mb-1.5 block text-[10px] text-[var(--ros-muted)]">Title</label><input required value={title} onChange={event => setTitle(event.target.value)} placeholder="A clear, memorable title" className="w-full px-3 py-2.5 text-xs"/></div></div><label className="mb-1.5 mt-3 block text-[10px] text-[var(--ros-muted)]">Durable context</label><textarea required value={content} onChange={event => setContent(event.target.value)} placeholder="Write what the team should remember and why it matters…" className="min-h-28 w-full resize-y px-3 py-2.5 text-xs"/><div className="mt-3 flex gap-2"><button className="btn-primary px-4 py-2 text-xs">Save to Brain</button><button type="button" onClick={() => setComposing(false)} className="btn-ghost px-4 py-2 text-xs">Cancel</button></div></form>}
    {!data ? <div className="mt-6 grid gap-3 md:grid-cols-3"><div className="sk h-48"/><div className="sk h-48"/><div className="sk h-48"/></div> : <div className="mt-6">{tab === 'overview' && <Overview data={data} setTab={setTab}/>} {tab === 'knowledge' && <ItemGrid icon={<BookOpen/>} items={data.knowledge} emptyTitle="No durable knowledge yet" emptyDescription="Capture strategy, customer insight and operating context the team should reuse."/>} {tab === 'decisions' && <ItemGrid icon={<Gavel/>} items={data.decisions} emptyTitle="No decisions recorded" emptyDescription="Record important choices and their reasoning so the team does not revisit settled ground."/>} {tab === 'memory' && <ItemGrid icon={<Lightbulb/>} items={data.memory} emptyTitle="Project memory is empty" emptyDescription="Save outcomes and lessons that should shape future work."/>} {tab === 'sources' && <Sources items={data.driveSources}/>}</div>}
  </div>
}

function Overview({ data, setTab }: { data: Data; setTab: (tab: Tab) => void }) { return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><section className="panel p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[rgba(126,208,173,.1)] text-[var(--ros-accent)]"><Brain className="w-4"/></span><div><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">Project constitution</h2><StatusPill tone={data.constitution ? 'good' : 'warn'}>{data.constitution ? 'Active' : 'Not created'}</StatusPill></div><p className="mt-2 text-[11px] leading-5 text-[var(--ros-faint)]">The enduring purpose, principles and boundaries that guide work in this project.</p></div></div>{data.constitution ? <div className="mt-5 rounded-xl bg-black/[.12] p-4"><h3 className="text-xs font-medium">{data.constitution.title}</h3><p className="mt-2 whitespace-pre-wrap text-[11px] leading-5 text-[var(--ros-muted)]">{data.constitution.content}</p></div> : <div className="mt-5"><button onClick={() => setTab('knowledge')} className="btn-ghost px-3 py-2 text-[10px]">Review Brain sections</button></div>}</section><section className="space-y-3">{([['Knowledge','Reusable project truth',data.knowledge.length,'knowledge',BookOpen],['Decisions','Choices with reasoning',data.decisions.length,'decisions',Gavel],['Memory','Outcomes and lessons',data.memory.length,'memory',Lightbulb],['Sources','Authorized source material',data.driveSources.length,'sources',HardDrive]] as const).map(([title,description,count,tab,Icon]) => <button key={title} onClick={() => setTab(tab)} className="panel panel-interactive flex w-full items-center gap-3 p-3.5 text-left"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/[.035] text-[var(--ros-muted)]"><Icon className="w-3.5"/></span><div className="flex-1"><p className="text-[11px] font-medium">{title}</p><p className="mt-1 text-[9px] text-[var(--ros-faint)]">{description}</p></div><strong className="text-sm">{count}</strong></button>)}</section></div> }
function ItemGrid({ icon, items, emptyTitle, emptyDescription }: { icon: ReactNode; items: BrainItem[]; emptyTitle:string; emptyDescription:string }) { if (!items.length) return <section className="panel"><EmptyState icon={icon} title={emptyTitle} description={emptyDescription}/></section>; return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item => <article key={item.id} className="panel p-4"><div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white/[.035] text-[var(--ros-muted)]">{icon}</span><div><h2 className="text-xs font-semibold">{item.title}</h2><p className="mt-2 line-clamp-6 whitespace-pre-wrap text-[10px] leading-5 text-[var(--ros-muted)]">{item.content || item.decision}</p></div></div></article>)}</div> }
function Sources({ items }: { items: Data['driveSources'] }) { return <div><div className="mb-4 flex items-center gap-3 rounded-xl bg-[rgba(126,208,173,.06)] px-4 py-3"><HardDrive className="w-4 text-[var(--ros-accent)]"/><p className="text-[10px] text-[var(--ros-muted)]"><strong className="text-[var(--ros-text)]">Sources inform the Brain.</strong> Google Drive remains an authorized read-only source, not the system of record.</p></div>{items.length ? <div className="grid gap-3 md:grid-cols-2">{items.map(item => <article key={item.id} className="panel flex items-center gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.035] text-[var(--ros-muted)]"><FileText className="w-4"/></span><div className="min-w-0 flex-1"><h2 className="truncate text-xs font-medium">{item.webUrl ? <a className="hover:text-[var(--ros-accent)]" href={item.webUrl} target="_blank" rel="noreferrer">{item.name}</a> : item.name}</h2><p className="mt-1 text-[9px] text-[var(--ros-faint)]">Google Drive · Read-only source</p></div><StatusPill tone={item.status === 'ACTIVE' || item.status === 'READY' ? 'good' : 'neutral'}>{item.status}</StatusPill></article>)}</div> : <section className="panel"><EmptyState icon={<HardDrive/>} title="No source material selected" description="Connect Google Drive in Tools, then explicitly choose the files this project may use."/></section>}</div> }
