'use client'

import { useCallback, useEffect, useState } from 'react'
import { FileText, FolderOpen, HardDrive, Search } from 'lucide-react'

import { EmptyState, PageHeader, StatusPill, friendlyLabel } from '@/components/rogeros-ui'

type Scope = { id: string; type: 'FILE' | 'FOLDER'; externalId: string; displayName: string; parentExternalId: string | null; updatedAt: string }
type Data = { state: string; installation: { id: string; status: string } | null; connection: { id: string; name: string; status: string; enabled: boolean; credential: { status: string; expiresAt: string | null; account: string } | null } | null; scopes: Scope[] }

const states: Record<string, string> = { CONNECTED: 'Connected', NEEDS_ATTENTION: 'Needs attention', DISABLED: 'Disabled', UNINSTALLED: 'Uninstalled' }

export function DriveWorkspace({ project }: { project: { id: string; name: string; slug: string; role: string } }) {
  const [data, setData] = useState<Data | null>(null); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true)
  const [folderId, setFolderId] = useState(''); const [fileId, setFileId] = useState(''); const [query, setQuery] = useState(''); const [result, setResult] = useState('')
  const canManage = project.role === 'OWNER' || project.role === 'ADMIN'
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/drive-workspace?projectId=${encodeURIComponent(project.id)}`, { cache: 'no-store' }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error === 'FORBIDDEN' ? 'Your project role is not authorized to browse Drive sources.' : 'Drive workspace state is unavailable.'); setData(body) } catch (error) { setNotice(error instanceof Error ? error.message : 'Drive workspace state is unavailable.') } finally { setLoading(false) } }, [project.id])
  useEffect(() => { void load() }, [load])
  const act = async (action: 'list' | 'search' | 'read') => { setNotice(''); setResult(''); try { const response = await fetch('/api/drive-workspace', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, action, parentId: folderId, fileId, query }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(message(body.error)); setResult(typeof body.resultText === 'string' ? body.resultText : 'No content returned.') } catch (error) { setNotice(error instanceof Error ? error.message : 'The Drive read could not be completed.') } }
  const saveScope = async (type: 'FILE' | 'FOLDER', externalId: string) => { if (!data?.connection || !externalId.trim()) return; try { const response = await fetch('/api/connections/google-drive/scopes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, connectionId: data.connection.id, type, externalId: externalId.trim() }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(message(body.error)); setNotice(`${body.scope?.displayName ?? 'Drive source'} is now available to this project.`); await load() } catch (error) { setNotice(error instanceof Error ? error.message : 'The scope could not be saved.') } }
  const state = data?.state ?? 'NEEDS_ATTENTION'
  return <div className="hq-rise"><PageHeader eyebrow={`${project.name} · Connected app`} title="Google Drive" description="Browse only the sources this project has explicitly selected." action={<StatusPill tone={state === 'CONNECTED' ? 'good' : state === 'UNINSTALLED' || state === 'DISABLED' ? 'neutral' : 'warn'}>{states[state] ?? friendlyLabel(state)}</StatusPill>} />
    <section className="panel mt-5 p-4 text-xs text-[var(--ros-muted)]"><div className="flex gap-3"><HardDrive className="mt-0.5 h-4 w-4 shrink-0 text-[var(--ros-accent)]"/><p><strong className="text-[var(--ros-text)]">Human read authorization: Owner and Admin only.</strong> This is separate from employee Tool permissions; no employee is impersonated. Active read policies may stop a workspace read, and this workspace never writes to Drive.</p></div></section>
    {notice && <p role="status" className="mt-4 rounded-xl border border-[var(--ros-line)] px-4 py-3 text-xs text-[var(--ros-muted)]">{notice}</p>}
    {loading ? <div className="panel mt-5 h-44 animate-pulse"/> : data ? <><section className="panel mt-5 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Connection and provenance</h2><p className="mt-1 text-[10px] text-[var(--ros-faint)]">{data.connection ? `${data.connection.name} · account ${data.connection.credential?.account ?? 'not connected'} · credential ${friendlyLabel(data.connection.credential?.status ?? 'unavailable')}` : 'No project Drive connection exists.'}</p></div>{canManage && <a className="btn-ghost px-3 py-2 text-[10px]" href={`/p/${project.slug}/tools`}>Manage in Tools</a>}</div></section>
      {state === 'CONNECTED' ? <><section className="mt-5 grid gap-4 lg:grid-cols-2"><section className="panel p-4"><h2 className="text-sm font-semibold">Approved folders</h2><p className="mt-1 text-[10px] text-[var(--ros-faint)]">List or search direct contents of a selected folder.</p><div className="mt-4 flex gap-2"><input aria-label="Selected folder ID" value={folderId} onChange={event => setFolderId(event.target.value)} placeholder="Folder ID" className="min-w-0 flex-1 px-3 py-2 text-xs"/><button className="btn-ghost px-3 py-2 text-xs" onClick={() => void act('list')}>List</button></div><div className="mt-2 flex gap-2"><input aria-label="Search selected folder" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name" className="min-w-0 flex-1 px-3 py-2 text-xs"/><button className="btn-ghost inline-flex items-center gap-1 px-3 py-2 text-xs" onClick={() => void act('search')}><Search className="h-3 w-3"/>Search</button></div>{canManage && <button className="mt-3 text-[10px] text-[var(--ros-accent)]" onClick={() => void saveScope('FOLDER', folderId)}>Allow this folder for the project</button>}</section><section className="panel p-4"><h2 className="text-sm font-semibold">Approved files</h2><p className="mt-1 text-[10px] text-[var(--ros-faint)]">Read supported content only from an explicitly selected file.</p><div className="mt-4 flex gap-2"><input aria-label="Selected file ID" value={fileId} onChange={event => setFileId(event.target.value)} placeholder="File ID" className="min-w-0 flex-1 px-3 py-2 text-xs"/><button className="btn-primary px-3 py-2 text-xs" onClick={() => void act('read')}>Read</button></div>{canManage && <button className="mt-3 text-[10px] text-[var(--ros-accent)]" onClick={() => void saveScope('FILE', fileId)}>Allow this file for the project</button>}</section></section>
      <section className="mt-5"><h2 className="mb-3 text-sm font-semibold">Explicit project sources</h2>{data.scopes.length ? <div className="grid gap-3 md:grid-cols-2">{data.scopes.map(scope => <article key={scope.id} className="panel flex items-center gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.035] text-[var(--ros-muted)]">{scope.type === 'FOLDER' ? <FolderOpen className="h-4 w-4"/> : <FileText className="h-4 w-4"/>}</span><div className="min-w-0"><h3 className="truncate text-xs font-medium">{scope.displayName}</h3><p className="mt-1 text-[10px] text-[var(--ros-faint)]">Google Drive · {scope.type === 'FOLDER' ? 'Folder browse' : 'Supported file read'}</p></div></article>)}</div> : <section className="panel"><EmptyState icon={<HardDrive/>} title="No source material selected" description="An Owner or Admin must explicitly add a file or folder before this project can browse it."/></section>}</section>
      {result && <section className="panel mt-5 p-4"><h2 className="text-sm font-semibold">Read-only result</h2><pre className="mt-3 max-h-[420px] overflow-auto whitespace-pre-wrap text-xs text-[var(--ros-muted)]">{result}</pre></section>}</> : <section className="panel mt-5"><EmptyState icon={<HardDrive/>} title={state === 'UNINSTALLED' ? 'Google Drive is not installed' : state === 'DISABLED' ? 'Google Drive is disabled' : 'Google Drive needs attention'} description="Use the governed Market and Tools connection lifecycle before browsing sources."/></section>}</> : null}</div>
}

function message(code: unknown) { const messages: Record<string, string> = { FORBIDDEN: 'Your project role is not authorized to browse Drive sources.', DRIVE_SCOPE_DENIED: 'That item is not an explicitly granted project source.', DRIVE_FILE_UNSUPPORTED: 'That source type is not supported for reading.', DRIVE_UNINSTALLED: 'Google Drive is not installed for this project.', DRIVE_DISABLED: 'Google Drive is disabled for this project.', DRIVE_NEEDS_ATTENTION: 'The Drive connection needs attention before it can be used.', DRIVE_HUMAN_POLICY_DENIED: 'An active project policy does not permit this human Drive read.', DRIVE_CREDENTIAL_UNAVAILABLE: 'The Drive credential is unavailable.', DRIVE_REFRESH_UNAVAILABLE: 'The Drive credential has expired and needs reconnection.', DRIVE_REFRESH_DENIED: 'The Drive credential needs reconnection.', INVALID_DRIVE_REQUEST: 'Choose an approved source before reading.' }; return typeof code === 'string' ? messages[code] ?? 'The Drive read could not be completed.' : 'The Drive read could not be completed.' }
