'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { signOut } from 'next-auth/react'
import { useEffect, useMemo, useState } from 'react'
import { Activity, AppWindow, Bot, Brain, CheckCircle2, ChevronDown, Command, FileBarChart, HardDrive, LayoutDashboard, Menu, Plus, Search, Settings, ShieldCheck, Sparkles, Trash2, Users, X } from 'lucide-react'
import { ThemeToggle } from '@/components/theme-toggle'
import type { ProjectSearchResult } from '@/lib/project-search'

type ShellProject = { id: string; name: string; slug: string; role?: string }
type SwitcherProject = { id: string; name: string; slug: string }
type NavItem = { label: string; path: string; icon: typeof LayoutDashboard; planned?: boolean }
const groups: Array<{ label: string; items: NavItem[] }> = [
  { label: 'Work', items: [{ label: 'Command Center', path: '', icon: LayoutDashboard }, { label: 'Team', path: 'team', icon: Users }, { label: 'Tasks', path: 'tasks', icon: CheckCircle2 }] },
  { label: 'Company', items: [{ label: 'Workforce', path: 'workforce', icon: Bot }, { label: 'Project Brain', path: 'brain', icon: Brain }, { label: 'Google Drive', path: 'drive', icon: HardDrive }, { label: 'Tools', path: 'tools', icon: AppWindow }, { label: 'Market', path: 'market', icon: Sparkles }] },
  { label: 'Control', items: [{ label: 'Approvals', path: 'approvals', icon: ShieldCheck }, { label: 'Reports', path: 'reports', icon: FileBarChart, planned: true }, { label: 'Automations', path: 'automations', icon: Activity, planned: true }] },
]

export function RogerOSShell({ children, project, projects, organization, accountLabel }: { children: React.ReactNode; project: ShellProject; projects: SwitcherProject[]; organization: string; accountLabel: string }) {
  const pathname = usePathname(); const router = useRouter(); const [mobileOpen, setMobileOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false); const [projectMenu, setProjectMenu] = useState(false); const [newProject, setNewProject] = useState(false); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [deleteStep,setDeleteStep]=useState(false)
  const suffix = pathname.split('/').slice(3).join('/'); const allItems = useMemo(() => groups.flatMap(group => group.items).filter(item => !item.planned), []); const initials = accountLabel.slice(0, 2).toUpperCase()
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(value => !value) } if (event.key === 'Escape') { setCommandOpen(false); setMobileOpen(false) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [])
  const hrefFor = (path: string) => `/p/${project.slug}${path ? `/${path}` : ''}`; const active = (path: string) => pathname === hrefFor(path)
  const navigation = <>{groups.map(group => <div key={group.label} className="rogeros-nav-group"><p>{group.label}</p>{group.items.map(item => { const Icon = item.icon; return <Link key={item.label} href={hrefFor(item.path)} onClick={() => setMobileOpen(false)} className={active(item.path) ? 'is-active' : ''}><Icon aria-hidden /><span>{item.label}</span>{item.planned && <small>Coming soon</small>}</Link> })}</div>)}</>

  const createProject=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,name,description})});if(r.ok){const d=await r.json();router.push(`/p/${d.project.slug}`);setNewProject(false)}}
  const deleteProject=async()=>{ const next=projects.find(p=>p.id!==project.id); const r=await fetch('/api/projects',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,deleteProjectId:project.id,confirmation:'DELETE'})}); if(r.ok) router.push(next?`/p/${next.slug}`:'/login') }
  return <div className="rogeros-app">
    <aside className={`rogeros-sidebar ${mobileOpen ? 'is-open' : ''}`} aria-label="Primary navigation"><div className="rogeros-brand"><span>R</span><div><strong>RogerOS</strong><small>by Green Pixxel</small></div><button className="rogeros-mobile-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X /></button></div><div className="rogeros-project-card"><small>Current project</small><strong>{project.name}</strong><span>{organization}</span></div><nav>{navigation}</nav><div className="rogeros-sidebar-footer"><Link href={`/p/${project.slug}/settings`}><Settings aria-hidden /> Settings</Link><button onClick={() => void signOut({ callbackUrl: '/login' })}><span className="rogeros-account-avatar">{initials}</span><span><strong>{accountLabel}</strong><small>{project.role ? friendlyRole(project.role) : 'Member'}</small></span></button></div></aside>
    {mobileOpen && <button className="rogeros-sidebar-backdrop" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}
    <div className="rogeros-main"><header className="rogeros-topbar"><button className="rogeros-menu-button" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu /></button><div className="relative"><button onClick={()=>setProjectMenu(v=>!v)} className="rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-left"><span className="block text-[9px] uppercase tracking-widest text-[var(--ros-faint)]">Project</span><span className="flex items-center gap-2 text-sm font-semibold">{project.name}<ChevronDown className="w-3.5"/></span></button>{projectMenu&&<div className="absolute left-0 top-full z-50 mt-2 w-72 rounded-2xl border border-white/10 bg-[#151915] p-2 shadow-2xl"><p className="px-3 py-2 text-[9px] uppercase tracking-widest text-[var(--ros-faint)]">Your projects</p>{projects.map(item=><button key={item.id} onClick={()=>router.push(`/p/${item.slug}${suffix?`/${suffix}`:''}`)} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-xs hover:bg-white/[.06]"><span>{item.name}</span>{item.id===project.id&&<span className="text-[9px] text-[var(--ros-accent)]">Current</span>}</button>)}<div className="my-2 border-t border-white/10"/><button onClick={()=>{setProjectMenu(false);setNewProject(true)}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-xs font-semibold text-[var(--ros-accent)] hover:bg-white/[.06]"><Plus className="w-4"/>Add project</button><button onClick={()=>setDeleteStep(true)} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-xs text-[var(--ros-bad)] hover:bg-white/[.06]"><Trash2 className="w-4"/>Delete current project</button></div>}</div><button className="rogeros-search-trigger" onClick={() => setCommandOpen(true)}><Search aria-hidden /><span>Search or go to…</span><kbd>Ctrl / ⌘ K</kbd></button><div className="rogeros-top-status">{organization}</div><ThemeToggle /><button className="rogeros-top-account" onClick={() => void signOut({ callbackUrl: '/login' })} title="Sign out">{initials}</button></header><main className="rogeros-content">{children}</main></div>
    {commandOpen && <ProjectCommandMenu projectId={project.id} items={allItems} hrefFor={hrefFor} onNavigate={path => { router.push(path); setCommandOpen(false) }} onClose={() => setCommandOpen(false)} />}
    {newProject&&<div className="rogeros-command-backdrop"><form onSubmit={createProject} className="rogeros-command"><header><div><strong>Create project</strong><span>Start a fresh, separate workspace.</span></div><button type="button" onClick={()=>setNewProject(false)}>Esc</button></header><div className="space-y-3 p-5"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Project name" maxLength={100}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this project for?" maxLength={500}/><button className="btn-primary w-full px-4 py-3 text-xs">Create project</button></div></form></div>}{deleteStep&&<div className="rogeros-command-backdrop"><div className="rogeros-command"><header><div><strong>{deleteStep?'Delete this project?':''}</strong><span>This permanently deletes its tasks, team data and connections.</span></div></header><div className="space-y-3 p-5"><button onClick={deleteProject} className="w-full rounded-xl bg-[var(--ros-bad)] px-4 py-3 text-xs font-semibold text-black">{deleteStep?'I understand — delete project':'Delete'}</button><button onClick={()=>setDeleteStep(false)} className="btn-ghost w-full px-4 py-3 text-xs">Cancel</button></div></div></div>}
  </div>
}

function ProjectCommandMenu({ projectId, items, hrefFor, onNavigate, onClose }: { projectId: string; items: NavItem[]; hrefFor: (path: string) => string; onNavigate: (path: string) => void; onClose: () => void }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<ProjectSearchResult[]>([]); const [error, setError] = useState('')
  useEffect(() => {
    const trimmed = query.trim()
    if (trimmed.length < 2) { setResults([]); setError(''); return }
    const controller = new AbortController()
    const timer = window.setTimeout(async () => {
      try {
        const response = await fetch(`/api/search?projectId=${encodeURIComponent(projectId)}&q=${encodeURIComponent(trimmed)}`, { cache: 'no-store', signal: controller.signal })
        if (!response.ok) throw new Error('SEARCH_UNAVAILABLE')
        const data = await response.json() as { results?: ProjectSearchResult[] }
        setResults(data.results ?? []); setError('')
      } catch { if (!controller.signal.aborted) { setResults([]); setError('Search is unavailable.') } }
    }, 150)
    return () => { controller.abort(); window.clearTimeout(timer) }
  }, [projectId, query])
  const matchingItems = items.filter(item => !query.trim() || item.label.toLowerCase().includes(query.trim().toLowerCase()))
  return <div className="rogeros-command-backdrop" role="presentation" onMouseDown={onClose}><div className="rogeros-command" role="dialog" aria-modal="true" aria-label="RogerOS search and command menu" onMouseDown={event => event.stopPropagation()}><header><Command aria-hidden /><div><strong>Search or go to</strong><span>Project records and navigation only</span></div><button aria-label="Close command menu" onClick={onClose}>Esc</button></header><div><label className="sr-only" htmlFor="rogeros-command-query">Search this project</label><input id="rogeros-command-query" autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search tasks, workforce, or Project Brain…" maxLength={100} /><p className="rogeros-command-note">Search returns redacted metadata only; it cannot run actions or change records.</p>{matchingItems.map(item => { const Icon = item.icon; return <button key={item.label} onClick={() => onNavigate(hrefFor(item.path))}><Icon aria-hidden /><span>{item.label}</span><small>Go to</small></button> })}{query.trim().length >= 2 && <><p className="rogeros-command-section">Project results</p>{results.map(result => <button key={`${result.kind}-${result.id}`} onClick={() => onNavigate(hrefFor(result.href))}><Search aria-hidden /><span><strong>{result.title}</strong><small>{result.detail}</small></span><small>Go to</small></button>)}{!error && results.length === 0 && <p className="rogeros-command-note">No authorized project records match.</p>}{error && <p className="rogeros-command-note">{error}</p>}</>}</div><footer>Navigation only. No actions, approvals, dispatches, or configuration changes are available here.</footer></div></div>
}

function friendlyRole(role: string) { return role.charAt(0) + role.slice(1).toLowerCase() }
