'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Bot, CalendarDays, Check, CheckSquare2, Columns3, List, Plus, RefreshCw, RotateCcw, Send, X } from 'lucide-react'

import { Avatar, EmptyState, PageHeader, StatusPill, friendlyLabel } from '@/components/rogeros-ui'

type RuntimeExecution = { id: string; status: string; resultText: string | null; errorMessage: string | null; reviewStatus: string | null; reviewedAt: string | null; reviewNote: string | null; createdAt: string; completedAt: string | null; runtime: { key: string } }
type EmployeeAssignment = { id: string; status: string; employee: { name: string; role: string } }
type Task = { id: string; title: string; description: string | null; status: string; priority: string; dueAt: string | null; updatedAt: string; relatedThread: { id: string; title: string | null } | null; assignments: Array<{ projectMember: { organizationMember: { user: { name: string | null; email: string | null } } } | null; employeeProjectAssignment?: { employee: { name: string }; runtimeAssignments?: Array<{ profileKey: string; runtime: { key: string } }> } | null }>; subtasks: Array<{ id: string; status: string }>; activities?: Array<{ id: string; detail: string | null; createdAt: string }>; hermesExecutions?: RuntimeExecution[] }
const statuses = ['BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'BLOCKED']
const priorities = ['LOW', 'MEDIUM', 'HIGH', 'URGENT']

export function TaskWorkspace({ project, currentMemberId }: { project: { id: string; name: string; role: string }; currentMemberId: string }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [view, setView] = useState<'board' | 'list'>('board'); const [selected, setSelected] = useState<Task | null>(null)
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [employeeProjectAssignmentId, setEmployeeProjectAssignmentId] = useState(''); const [employees, setEmployees] = useState<EmployeeAssignment[]>([])
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [dispatching, setDispatching] = useState(false); const [creating, setCreating] = useState(false); const [reviewing, setReviewing] = useState(''); const [reviewNote, setReviewNote] = useState('')
  const query = useMemo(() => `projectId=${encodeURIComponent(project.id)}`, [project.id])
  const load = useCallback(async () => { const [taskResponse, workforceResponse] = await Promise.all([fetch(`/api/tasks2?${query}`), fetch(`/api/workforce?${query}`)]); if (!taskResponse.ok) throw Error(); setTasks((await taskResponse.json()).tasks); if (workforceResponse.ok) setEmployees((await workforceResponse.json()).employees) }, [query])
  const reloadSelected = useCallback(async (id: string) => { const response = await fetch(`/api/tasks2/${id}?${query}`); if (!response.ok) throw Error(); setSelected((await response.json()).task) }, [query])
  useEffect(() => { load().catch(() => setError('We could not load this project’s tasks.')).finally(() => setLoading(false)) }, [load])
  const create = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; const response = await fetch('/api/tasks2', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, title, description, projectMemberId: employeeProjectAssignmentId ? undefined : currentMemberId, employeeProjectAssignmentId: employeeProjectAssignmentId || undefined }) }); if (!response.ok) { setError('The task could not be created.'); return } setTitle(''); setDescription(''); setEmployeeProjectAssignmentId(''); setCreating(false); await load() }
  const patch = async (id: string, data: object) => { const response = await fetch(`/api/tasks2/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, ...data }) }); if (!response.ok) { setError('The task could not be updated.'); return } await load(); if (selected) await reloadSelected(id) }
  const open = async (task: Task) => { try { await reloadSelected(task.id) } catch { setError('That task is no longer available.') } }
  const dispatch = async () => { if (!selected) return; setDispatching(true); setError(''); try { const response = await fetch('/api/runtime/dispatch', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, taskId: selected.id }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || 'Dispatch failed') } await Promise.all([reloadSelected(selected.id), load()]) } catch (dispatchError) { setError(dispatchError instanceof Error ? dispatchError.message : 'The AI employee could not start this task.') } finally { setDispatching(false) } }
  const refresh = async (executionId: string) => { if (!selected) return; const response = await fetch(`/api/runtime/executions/${executionId}/refresh`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id }) }); if (!response.ok) { setError('The AI work status could not be refreshed.'); return } await reloadSelected(selected.id) }
  const review = async (executionId: string, action: 'ACCEPT' | 'REQUEST_REVISION') => { if (!selected) return; setReviewing(action); setError(''); try { const response = await fetch(`/api/runtime/executions/${executionId}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, action, note: reviewNote }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || 'Review failed') } setReviewNote(''); await Promise.all([reloadSelected(selected.id), load()]) } catch { setError('The review could not be saved safely.') } finally { setReviewing('') } }
  const retry = async (executionId: string) => { if (!selected) return; setDispatching(true); setError(''); try { const response = await fetch(`/api/runtime/executions/${executionId}/retry`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || 'Retry failed') } await Promise.all([reloadSelected(selected.id), load()]) } catch { setError('The AI work could not be retried safely.') } finally { setDispatching(false) } }
  const assignee = (task: Task) => task.assignments[0]?.employeeProjectAssignment?.employee.name || task.assignments[0]?.projectMember?.organizationMember.user.name || 'Unassigned'
  const runtime = selected?.assignments.find(assignment => assignment.employeeProjectAssignment?.runtimeAssignments?.[0])?.employeeProjectAssignment?.runtimeAssignments?.[0]
  const canDispatch = ['OWNER','ADMIN','OPERATOR'].includes(project.role)
  const canReview = ['OWNER','ADMIN','APPROVER'].includes(project.role)
  const latestExecution = selected?.hermesExecutions?.[0]
  const activeExecution = latestExecution && ['QUEUED','DISPATCHING','RUNNING'].includes(latestExecution.status)
  useEffect(() => { if (!selected?.id || !activeExecution) return; const timer = window.setInterval(() => { void reloadSelected(selected.id) }, 3000); return () => window.clearInterval(timer) }, [activeExecution, reloadSelected, selected?.id])

  return <div className="hq-rise">
    <PageHeader eyebrow={`${project.name} · Work`} title="Tasks" description="Plan outcomes, assign ownership and follow AI execution without losing the authoritative work record." action={<button onClick={() => setCreating(value => !value)} className="btn-primary inline-flex items-center gap-2 px-3 py-2 text-xs"><Plus className="w-3.5"/> New task</button>} />
    {error && <div role="alert" className="mb-4 rounded-xl border border-[rgba(235,130,122,.25)] bg-[rgba(235,130,122,.08)] px-4 py-3 text-xs text-[var(--ros-bad)]">{error}</div>}
    {creating && <form onSubmit={create} className="panel mb-5 grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_250px]"><div><label className="mb-1.5 block text-[10px] font-medium text-[var(--ros-muted)]">Outcome</label><input required value={title} onChange={event => setTitle(event.target.value)} placeholder="What should be accomplished?" className="w-full px-3 py-2.5 text-xs"/></div><div><label className="mb-1.5 block text-[10px] font-medium text-[var(--ros-muted)]">Owner</label><select aria-label="Assign employee" value={employeeProjectAssignmentId} onChange={event => setEmployeeProjectAssignmentId(event.target.value)} className="w-full px-3 py-2.5 text-xs"><option value="">Assign to me</option>{employees.filter(employee => employee.status === 'ACTIVE').map(employee => <option key={employee.id} value={employee.id}>{employee.employee.name} · {employee.employee.role}</option>)}</select></div><div className="md:col-span-2"><label className="mb-1.5 block text-[10px] font-medium text-[var(--ros-muted)]">Brief</label><textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Add the context and definition of done…" className="min-h-20 w-full resize-y px-3 py-2.5 text-xs"/></div><div className="flex gap-2 md:col-span-2"><button className="btn-primary px-4 py-2 text-xs">Create task</button><button type="button" onClick={() => setCreating(false)} className="btn-ghost px-4 py-2 text-xs">Cancel</button></div></form>}
    <div className="mb-4 flex items-center justify-between"><p className="text-[10px] text-[var(--ros-faint)]">{tasks.length} task{tasks.length === 1 ? '' : 's'} in this project</p><div className="flex rounded-lg border border-[var(--ros-line)] p-1"><button aria-label="Board view" onClick={() => setView('board')} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[10px] ${view === 'board' ? 'bg-white/[.07] text-[var(--ros-text)]' : 'text-[var(--ros-faint)]'}`}><Columns3 className="w-3"/> Board</button><button aria-label="List view" onClick={() => setView('list')} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[10px] ${view === 'list' ? 'bg-white/[.07] text-[var(--ros-text)]' : 'text-[var(--ros-faint)]'}`}><List className="w-3"/> List</button></div></div>
    {loading ? <div className="grid gap-3 md:grid-cols-3"><div className="sk h-56"/><div className="sk h-56"/><div className="sk h-56"/></div> : tasks.length === 0 ? <section className="panel"><EmptyState icon={<CheckSquare2 />} title="Your project has no tasks yet" description="Create the first outcome and assign it to yourself or an AI employee." action={<button onClick={() => setCreating(true)} className="btn-primary px-3 py-2 text-xs">Create the first task</button>} /></section> : view === 'board' ? <div className="overflow-x-auto pb-3"><div className="grid min-w-[1080px] grid-cols-6 gap-3">{statuses.map(status => <section key={status} className="rounded-xl border border-[var(--ros-line)] bg-black/[.08] p-2"><header className="flex items-center justify-between px-1 py-2"><h2 className="text-[9px] font-bold uppercase tracking-[.11em] text-[var(--ros-muted)]">{friendlyLabel(status)}</h2><span className="text-[9px] text-[var(--ros-faint)]">{tasks.filter(task => task.status === status).length}</span></header>{tasks.filter(task => task.status === status).map(task => <TaskCard key={task.id} task={task} assignee={assignee(task)} onOpen={() => void open(task)}/>)}</section>)}</div></div> : <div className="overflow-x-auto rounded-xl border border-[var(--ros-line)] bg-[var(--ros-surface)]"><table className="w-full min-w-[760px] text-left text-[11px]"><thead className="border-b border-[var(--ros-line)] text-[9px] uppercase tracking-[.1em] text-[var(--ros-faint)]"><tr><th className="p-3.5">Task</th><th>Status</th><th>Priority</th><th>Owner</th><th>Due</th></tr></thead><tbody>{tasks.map(task => <tr key={task.id} onClick={() => void open(task)} className="cursor-pointer border-b border-[var(--ros-line)] hover:bg-white/[.025]"><td className="p-3.5 font-medium text-[var(--ros-text)]">{task.title}</td><td><StatusPill tone={statusTone(task.status)}>{friendlyLabel(task.status)}</StatusPill></td><td>{friendlyLabel(task.priority)}</td><td><span className="inline-flex items-center gap-2"><Avatar name={assignee(task)} size="sm"/>{assignee(task)}</span></td><td>{task.dueAt ? new Date(task.dueAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></div>}
    {selected && <><button className="fixed inset-0 z-40 bg-black/55" aria-label="Close task details" onClick={() => setSelected(null)}/><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-[470px] overflow-y-auto border-l border-[var(--ros-line)] bg-[var(--ros-surface-raised)] p-5 shadow-2xl"><div className="flex items-center justify-between"><p className="eyebrow">Task details</p><button onClick={() => setSelected(null)} aria-label="Close task details" className="text-[var(--ros-faint)]"><X className="w-5"/></button></div><h2 className="mt-4 text-xl font-semibold tracking-[-.02em]">{selected.title}</h2><p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-[var(--ros-muted)]">{selected.description || 'No brief has been added yet.'}</p><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-[9px] uppercase tracking-[.1em] text-[var(--ros-faint)]">Status<select value={selected.status} onChange={event => void patch(selected.id, { status: event.target.value })} className="mt-1.5 w-full p-2 text-xs">{statuses.map(status => <option key={status}>{status}</option>)}<option>CANCELLED</option></select></label><label className="text-[9px] uppercase tracking-[.1em] text-[var(--ros-faint)]">Priority<select value={selected.priority} onChange={event => void patch(selected.id, { priority: event.target.value })} className="mt-1.5 w-full p-2 text-xs">{priorities.map(priority => <option key={priority}>{priority}</option>)}</select></label></div><button onClick={() => void patch(selected.id, { projectMemberId: currentMemberId })} className="btn-ghost mt-3 px-3 py-2 text-xs">Assign to me</button>
      <section className="panel mt-6 p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[rgba(126,208,173,.1)] text-[var(--ros-accent)]"><Bot className="w-4"/></span><div><h3 className="text-xs font-semibold">AI work</h3><p className="mt-1 text-[10px] text-[var(--ros-faint)]">{runtime ? activeExecution ? 'Your AI employee is working. This page can be closed safely.' : latestExecution?.reviewStatus === 'PENDING' ? 'The result is ready for human review.' : 'An AI employee is connected to this task.' : 'No AI employee is assigned to this task owner.'}</p></div></div>
        {runtime && canDispatch && !latestExecution && <button disabled={dispatching} onClick={() => void dispatch()} className="btn-primary mt-4 inline-flex items-center gap-2 px-3 py-2 text-xs">{dispatching ? <RefreshCw className="w-3 animate-spin"/> : <Send className="w-3"/>}{dispatching ? 'Starting work…' : 'Start AI work'}</button>}
        {runtime && canDispatch && latestExecution?.reviewStatus === 'REVISION_REQUESTED' && selected.status === 'TODO' && <button disabled={dispatching} onClick={() => void dispatch()} className="btn-primary mt-4 inline-flex items-center gap-2 px-3 py-2 text-xs"><RotateCcw className="w-3"/>{dispatching ? 'Starting revision…' : 'Start revised work'}</button>}
        {runtime && <details className="mt-3 text-[9px] text-[var(--ros-faint)]"><summary className="cursor-pointer">Technical details</summary><p className="mt-2">Runtime {runtime.runtime.key}</p></details>}
        {(selected.hermesExecutions || []).map((execution, index) => <article key={execution.id} className="mt-4 border-t border-[var(--ros-line)] pt-4"><div className="flex items-center justify-between"><StatusPill tone={execution.status === 'SUCCEEDED' ? 'good' : execution.status === 'FAILED' ? 'bad' : 'warn'}>{executionLabel(execution)}</StatusPill>{index === 0 && ['QUEUED','DISPATCHING','RUNNING'].includes(execution.status) && <button onClick={() => void refresh(execution.id)} className="inline-flex items-center gap-1 text-[10px] text-[var(--ros-accent)]"><RefreshCw className="w-3"/> Check now</button>}</div>{execution.resultText && <div className="mt-3 whitespace-pre-wrap rounded-lg bg-[var(--ros-surface)] p-3 text-[11px] leading-5 text-[var(--ros-muted)]">{execution.resultText}</div>}{execution.errorMessage && <p className="mt-3 text-[10px] text-[var(--ros-bad)]">The AI work could not complete. No unsafe runtime details were exposed.</p>}{index === 0 && execution.status === 'FAILED' && canDispatch && <button disabled={dispatching} onClick={() => void retry(execution.id)} className="btn-primary mt-3 inline-flex items-center gap-2 px-3 py-2 text-xs"><RotateCcw className="w-3"/>{dispatching ? 'Retrying…' : 'Retry safely'}</button>}{index === 0 && execution.status === 'SUCCEEDED' && execution.reviewStatus === 'PENDING' && canReview && <div className="mt-4 space-y-3"><textarea aria-label="Review note" value={reviewNote} onChange={event => setReviewNote(event.target.value)} maxLength={2000} placeholder="Optional review note or revision guidance" className="min-h-20 w-full resize-y p-3 text-xs"/><div className="flex flex-wrap gap-2"><button disabled={Boolean(reviewing)} onClick={() => void review(execution.id, 'ACCEPT')} className="btn-primary inline-flex items-center gap-2 px-3 py-2 text-xs"><Check className="w-3"/>{reviewing === 'ACCEPT' ? 'Accepting…' : 'Accept result'}</button><button disabled={Boolean(reviewing)} onClick={() => void review(execution.id, 'REQUEST_REVISION')} className="btn-ghost inline-flex items-center gap-2 px-3 py-2 text-xs"><RotateCcw className="w-3"/>{reviewing === 'REQUEST_REVISION' ? 'Saving…' : 'Request revision'}</button></div></div>}{execution.reviewNote && <p className="mt-3 rounded-lg border border-[var(--ros-line)] p-3 text-[10px] text-[var(--ros-muted)]"><strong className="block text-[var(--ros-text)]">Review note</strong>{execution.reviewNote}</p>}<p className="mt-2 text-[9px] text-[var(--ros-faint)]">Started {new Date(execution.createdAt).toLocaleString()}</p></article>)}
      </section><div className="mt-6"><h3 className="text-xs font-semibold">Activity</h3>{selected.activities?.length ? selected.activities.map(activity => <div key={activity.id} className="mt-3 border-l border-[var(--ros-line-strong)] pl-3"><p className="text-[10px] text-[var(--ros-muted)]">{activity.detail || 'Task updated'}</p><p className="mt-1 text-[9px] text-[var(--ros-faint)]">{new Date(activity.createdAt).toLocaleString()}</p></div>) : <p className="mt-2 text-[10px] text-[var(--ros-faint)]">No recorded activity yet.</p>}</div></aside></>}
  </div>
}

function TaskCard({ task, assignee, onOpen }: { task: Task; assignee: string; onOpen: () => void }) { return <button onClick={onOpen} className="mb-2 w-full rounded-lg border border-[var(--ros-line)] bg-[var(--ros-surface)] p-3 text-left transition hover:border-[var(--ros-line-strong)] hover:bg-[var(--ros-surface-raised)]"><div className="flex items-start justify-between gap-2"><strong className="text-[11px] leading-4 text-[var(--ros-text)]">{task.title}</strong><span className={`mt-1 h-1.5 w-1.5 shrink-0 rounded-full ${priorityDot(task.priority)}`} /></div><div className="mt-3 flex items-center gap-2"><Avatar name={assignee} size="sm"/><span className="min-w-0 flex-1 truncate text-[9px] text-[var(--ros-faint)]">{assignee}</span></div>{task.dueAt && <p className="mt-2 flex items-center gap-1 text-[9px] text-[var(--ros-faint)]"><CalendarDays className="w-3"/> {new Date(task.dueAt).toLocaleDateString()}</p>}</button> }
function priorityDot(priority: string) { return priority === 'URGENT' ? 'bg-[var(--ros-bad)]' : priority === 'HIGH' ? 'bg-[var(--ros-warn)]' : priority === 'MEDIUM' ? 'bg-[var(--ros-accent)]' : 'bg-[var(--ros-faint)]' }
function statusTone(status: string): 'good' | 'warn' | 'bad' | 'neutral' { return status === 'DONE' ? 'good' : status === 'BLOCKED' ? 'bad' : status === 'REVIEW' ? 'warn' : 'neutral' }
function executionLabel(execution: RuntimeExecution) { if (execution.reviewStatus === 'ACCEPTED') return 'Completed'; if (execution.reviewStatus === 'REVISION_REQUESTED') return 'Revision requested'; if (execution.status === 'SUCCEEDED') return 'Ready for review'; if (execution.status === 'FAILED') return 'Needs attention'; return 'Working' }
