'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Hash, ListTodo, MessageCircle, MessagesSquare, Send, X } from 'lucide-react'

import { Avatar, EmptyState, PageHeader, StatusPill, friendlyLabel } from '@/components/rogeros-ui'

type Participant = { systemIdentity: string | null; user: { name: string | null; email: string | null } | null }
type Conversation = { id: string; type: 'DIRECT' | 'GROUP' | 'CHANNEL'; slug: string | null; title: string | null; participants: Participant[]; _count: { messages: number } }
type Message = { id: string; body: string; createdAt: string; authorSystemIdentity: string | null; author: { name: string | null; email: string | null } | null; rootForThread?: { id: string; status: string; _count: { replies: number } } | null }
type Thread = { id: string; title: string | null; status: 'OPEN' | 'RESOLVED' | 'ARCHIVED'; rootMessage: Message; relatedTasks?: Array<{ id: string; title: string; status: string }> }

const conversationLabel = (conversation: Conversation) => conversation.title || (conversation.participants.find(participant => participant.systemIdentity)?.systemIdentity === 'chief-of-staff' ? 'Chief of Staff' : 'Untitled conversation')
const messageName = (message: Message) => message.authorSystemIdentity === 'chief-of-staff' ? 'Chief of Staff' : message.author?.name || message.author?.email || 'Unknown'

export function TeamWorkspace({ project }: { project: { id: string; name: string } }) {
  const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<string | null>(null); const [messages, setMessages] = useState<Message[]>([])
  const [thread, setThread] = useState<Thread | null>(null); const [replies, setReplies] = useState<Message[]>([]); const [message, setMessage] = useState(''); const [reply, setReply] = useState('')
  const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState('')
  const query = useMemo(() => `projectId=${encodeURIComponent(project.id)}`, [project.id])
  const loadConversations = useCallback(async () => { const response = await fetch(`/api/team/conversations?${query}`); if (!response.ok) throw new Error(); const data = await response.json(); setConversations(data.conversations); setSelected(current => current && data.conversations.some((conversation: Conversation) => conversation.id === current) ? current : data.conversations[0]?.id ?? null) }, [query])
  const loadMessages = useCallback(async (conversationId: string) => { const response = await fetch(`/api/team/conversations/${conversationId}?${query}`); if (!response.ok) throw new Error(); setMessages((await response.json()).messages) }, [query])
  useEffect(() => { loadConversations().catch(() => setError('We could not load this project’s conversations.')).finally(() => setLoading(false)) }, [loadConversations])
  useEffect(() => { if (selected) loadMessages(selected).catch(() => setError('We could not open this conversation.')); else setMessages([]); setThread(null); setReplies([]) }, [selected, loadMessages])

  const openThread = async (root: Message) => { if (!selected) return; try { let id = root.rootForThread?.id; if (!id) { const response = await fetch('/api/team/threads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, conversationId: selected, rootMessageId: root.id }) }); if (!response.ok) throw new Error(); id = (await response.json()).thread.id; await loadMessages(selected) } const response = await fetch(`/api/team/threads/${id}?${query}`); if (!response.ok) throw new Error(); const data = await response.json(); setThread(data.thread); setReplies(data.replies) } catch { setError('We could not open this focused topic.') } }
  const sendMessage = async (event: FormEvent) => { event.preventDefault(); if (!selected || !message.trim()) return; setSending(true); try { const response = await fetch(`/api/team/conversations/${selected}?${query}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body: message }) }); if (!response.ok) throw new Error(); setMessage(''); await Promise.all([loadMessages(selected), loadConversations()]) } catch { setError('Your message could not be sent.') } finally { setSending(false) } }
  const sendReply = async (event: FormEvent) => { event.preventDefault(); if (!thread || !reply.trim()) return; try { const response = await fetch(`/api/team/threads/${thread.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, body: reply }) }); if (!response.ok) throw new Error(); setReply(''); const data = await (await fetch(`/api/team/threads/${thread.id}?${query}`)).json(); setReplies(data.replies); if (selected) await loadMessages(selected) } catch { setError('Your reply could not be sent.') } }
  const changeStatus = async (status: Thread['status']) => { if (!thread) return; try { const response = await fetch(`/api/team/threads/${thread.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, status }) }); if (!response.ok) throw new Error(); setThread({ ...thread, status }) } catch { setError('The topic status could not be changed.') } }
  const createTaskFromThread = async () => { if (!thread) return; try { const response = await fetch('/api/tasks2', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, title: thread.title || thread.rootMessage.body.slice(0, 200), relatedThreadId: thread.id }) }); if (!response.ok) throw new Error(); const task = (await response.json()).task; setThread({ ...thread, relatedTasks: [...(thread.relatedTasks || []), { id: task.id, title: task.title, status: task.status }] }) } catch { setError('A linked task could not be created.') } }
  const current = conversations.find(conversation => conversation.id === selected)

  return <div className="hq-rise">
    <PageHeader eyebrow={`${project.name} · Team`} title="Conversations that move work forward" description="Talk with your team, keep focused topics in threads, and turn decisions into project tasks." action={<StatusPill tone="good">Project-scoped</StatusPill>} />
    {error && <div role="alert" className="mb-4 rounded-xl border border-[rgba(235,130,122,.25)] bg-[rgba(235,130,122,.08)] px-4 py-3 text-xs text-[var(--ros-bad)]">{error}</div>}
    <div className="grid min-h-[680px] overflow-hidden rounded-2xl border border-[var(--ros-line)] bg-[var(--ros-surface)] lg:grid-cols-[245px_minmax(0,1fr)_320px]">
      <aside className="border-b border-[var(--ros-line)] p-3 lg:border-b-0 lg:border-r">
        <div className="mb-2 flex items-center justify-between px-2 py-2"><p className="eyebrow">Conversations</p><MessagesSquare className="w-4 text-[var(--ros-faint)]" /></div>
        {loading ? <div className="space-y-2 p-2"><div className="sk h-10"/><div className="sk h-10"/><div className="sk h-10"/></div> : <>
          <p className="px-2 pb-2 pt-1 text-[9px] font-bold uppercase tracking-[.12em] text-[var(--ros-faint)]">Channels</p>
          {conversations.filter(item => item.type !== 'DIRECT').map(item => <ConversationButton key={item.id} conversation={item} selected={selected === item.id} onClick={() => setSelected(item.id)} />)}
          <p className="mt-5 px-2 pb-2 text-[9px] font-bold uppercase tracking-[.12em] text-[var(--ros-faint)]">Direct</p>
          {conversations.filter(item => item.type === 'DIRECT').map(item => <ConversationButton key={item.id} conversation={item} selected={selected === item.id} onClick={() => setSelected(item.id)} />)}
        </>}
      </aside>

      <section className="flex min-w-0 flex-col border-b border-[var(--ros-line)] lg:border-b-0 lg:border-r">
        <header className="flex min-h-[68px] items-center gap-3 border-b border-[var(--ros-line)] px-5"><Avatar name={current ? conversationLabel(current) : project.name} /><div className="min-w-0"><h2 className="truncate text-sm font-semibold">{current ? conversationLabel(current) : 'Choose a conversation'}</h2><p className="mt-1 text-[10px] text-[var(--ros-faint)]">{current ? `${current._count.messages} message${current._count.messages === 1 ? '' : 's'} · ${friendlyLabel(current.type)}` : 'Your conversations stay inside this project'}</p></div></header>
        <div className="flex-1 space-y-5 overflow-y-auto p-5">
          {!selected ? <EmptyState icon={<MessageCircle />} title="Choose a conversation" description="Select a channel or teammate to see the project history." /> : messages.length === 0 ? <EmptyState icon={<MessageCircle />} title="Start the conversation" description="Share context, make a decision, or ask your Chief of Staff for help." /> : messages.map(item => <article key={item.id} className="group flex gap-3"><Avatar name={messageName(item)} size="sm"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2"><strong className="text-[12px]">{messageName(item)}</strong><time className="text-[9px] text-[var(--ros-faint)]">{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-1 whitespace-pre-wrap text-[12px] leading-5 text-[var(--ros-muted)]">{item.body}</p><button onClick={() => void openThread(item)} className="mt-2 text-[10px] font-medium text-[var(--ros-accent)]">{item.rootForThread ? `${item.rootForThread._count.replies} replies · Open topic` : 'Reply in a focused topic'}</button></div></article>)}
        </div>
        {selected && <form onSubmit={sendMessage} className="border-t border-[var(--ros-line)] p-4"><div className="rounded-xl border border-[var(--ros-line)] bg-black/10 p-2 focus-within:border-[rgba(126,208,173,.38)]"><textarea aria-label="Message" value={message} onChange={event => setMessage(event.target.value)} placeholder={`Message ${current ? conversationLabel(current) : 'this conversation'}…`} className="min-h-16 w-full resize-none border-0 bg-transparent px-2 py-1 text-[12px] shadow-none focus:shadow-none"/><div className="flex items-center justify-between px-1 pt-1"><span className="text-[9px] text-[var(--ros-faint)]">Project conversation</span><button disabled={sending || !message.trim()} className="btn-primary inline-flex items-center gap-2 px-3 py-2 text-[11px]" type="submit">{sending ? 'Sending…' : 'Send'} <Send className="w-3"/></button></div></div></form>}
      </section>

      <aside className="flex min-h-72 flex-col bg-black/[.08]">{thread ? <>
        <header className="border-b border-[var(--ros-line)] p-4"><div className="flex items-center justify-between"><div><p className="eyebrow">Focused topic</p><h2 className="mt-1 text-sm font-semibold">Thread</h2></div><button onClick={() => setThread(null)} aria-label="Close thread" className="text-[var(--ros-faint)]"><X className="w-4"/></button></div><p className="mt-3 line-clamp-3 text-[11px] leading-5 text-[var(--ros-muted)]">{thread.title || thread.rootMessage.body}</p><div className="mt-3 flex items-center gap-2"><select aria-label="Thread status" value={thread.status} onChange={event => void changeStatus(event.target.value as Thread['status'])} className="px-2 py-1.5 text-[10px]"><option value="OPEN">Open</option><option value="RESOLVED">Resolved</option><option value="ARCHIVED">Archived</option></select><button onClick={() => void createTaskFromThread()} className="btn-ghost inline-flex items-center gap-1.5 px-2 py-1.5 text-[10px]"><ListTodo className="w-3"/> Create task</button></div>{thread.relatedTasks?.map(task => <p key={task.id} className="mt-2 text-[10px] text-[var(--ros-accent)]">Task · {task.title}</p>)}</header>
        <div className="flex-1 space-y-4 overflow-y-auto p-4"><ThreadMessage message={thread.rootMessage}/>{replies.map(item => <ThreadMessage key={item.id} message={item}/>)}</div>
        <form onSubmit={sendReply} className="border-t border-[var(--ros-line)] p-4"><textarea aria-label="Reply" value={reply} onChange={event => setReply(event.target.value)} placeholder="Reply to this topic…" className="min-h-16 w-full resize-none p-2 text-[11px]"/><button disabled={!reply.trim()} className="btn-primary mt-2 w-full py-2 text-[11px]">Reply</button></form>
      </> : <EmptyState icon={<MessageCircle />} title="Focused topics" description="Open a message thread to discuss one topic without losing the main conversation." />}</aside>
    </div>
  </div>
}

function ConversationButton({ conversation, selected, onClick }: { conversation: Conversation; selected: boolean; onClick: () => void }) { const title = conversationLabel(conversation); return <button onClick={onClick} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left transition-colors ${selected ? 'bg-[rgba(126,208,173,.09)] text-[var(--ros-accent-strong)]' : 'text-[var(--ros-muted)] hover:bg-white/[.03]'}`}>{conversation.type === 'DIRECT' ? <Avatar name={title} size="sm"/> : <span className="grid h-7 w-7 place-items-center rounded-lg bg-white/[.035]"><Hash className="w-3.5"/></span>}<span className="min-w-0 flex-1 truncate text-[11px] font-medium">{title}</span>{conversation._count.messages > 0 && <small className="text-[9px] text-[var(--ros-faint)]">{conversation._count.messages}</small>}</button> }
function ThreadMessage({ message }: { message: Message }) { const author = messageName(message); return <article className="flex gap-2.5"><Avatar name={author} size="sm"/><div><strong className="text-[11px]">{author}</strong><p className="mt-1 whitespace-pre-wrap text-[11px] leading-5 text-[var(--ros-muted)]">{message.body}</p></div></article> }
