'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'

type Participant = { systemIdentity: string | null; user: { name: string | null; email: string | null } | null }
type Conversation = { id: string; type: 'DIRECT' | 'GROUP' | 'CHANNEL'; slug: string | null; title: string | null; participants: Participant[]; _count: { messages: number } }
type Message = { id: string; body: string; createdAt: string; authorSystemIdentity: string | null; author: { name: string | null; email: string | null } | null; rootForThread?: { id: string; status: string; _count: { replies: number } } | null }
type Thread = { id: string; title: string | null; status: 'OPEN' | 'RESOLVED' | 'ARCHIVED'; rootMessage: Message; relatedTasks?: Array<{ id: string; title: string; status: string }> }

const label = (conversation: Conversation) => conversation.title || (conversation.participants.find(p => p.systemIdentity)?.systemIdentity === 'chief-of-staff' ? 'Chief of Staff' : 'Untitled conversation')
const name = (message: Message) => message.authorSystemIdentity === 'chief-of-staff' ? 'Chief of Staff' : message.author?.name || message.author?.email || 'Unknown'

export function TeamWorkspace({ project }: { project: { id: string; name: string } }) {
  const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<string | null>(null)
  const [messages, setMessages] = useState<Message[]>([]); const [thread, setThread] = useState<Thread | null>(null); const [replies, setReplies] = useState<Message[]>([])
  const [message, setMessage] = useState(''); const [reply, setReply] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const query = useMemo(() => `projectId=${encodeURIComponent(project.id)}`, [project.id])
  const loadConversations = useCallback(async () => { const r = await fetch(`/api/team/conversations?${query}`); if (!r.ok) throw new Error('Unable to load conversations'); const data = await r.json(); setConversations(data.conversations); setSelected(current => current && data.conversations.some((c: Conversation) => c.id === current) ? current : data.conversations[0]?.id ?? null) }, [query])
  useEffect(() => { loadConversations().catch(() => setError('Unable to load this project’s Team workspace.')).finally(() => setLoading(false)) }, [loadConversations])
  const loadMessages = useCallback(async (conversationId: string) => { const r = await fetch(`/api/team/conversations/${conversationId}?${query}`); if (!r.ok) throw new Error('Unable to load messages'); const data = await r.json(); setMessages(data.messages) }, [query])
  useEffect(() => { if (selected) loadMessages(selected).catch(() => setError('Unable to load this conversation.')); else setMessages([]); setThread(null); setReplies([]) }, [selected, loadMessages])
  const openThread = async (message: Message) => { if (!selected) return; try { let id = message.rootForThread?.id; if (!id) { const r = await fetch('/api/team/threads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, conversationId: selected, rootMessageId: message.id }) }); if (!r.ok) throw new Error(); id = (await r.json()).thread.id; await loadMessages(selected) } const r = await fetch(`/api/team/threads/${id}?${query}`); if (!r.ok) throw new Error(); const data = await r.json(); setThread(data.thread); setReplies(data.replies) } catch { setError('Unable to open this thread.') } }
  const sendMessage = async (event: FormEvent) => { event.preventDefault(); if (!selected || !message.trim()) return; try { const r = await fetch(`/api/team/conversations/${selected}?${query}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body: message }) }); if (!r.ok) throw new Error(); setMessage(''); await loadMessages(selected); await loadConversations() } catch { setError('Unable to send the message.') } }
  const sendReply = async (event: FormEvent) => { event.preventDefault(); if (!thread || !reply.trim()) return; try { const r = await fetch(`/api/team/threads/${thread.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, body: reply }) }); if (!r.ok) throw new Error(); setReply(''); const data = await (await fetch(`/api/team/threads/${thread.id}?${query}`)).json(); setReplies(data.replies); if (selected) await loadMessages(selected) } catch { setError('Unable to send the thread reply.') } }
  const changeStatus = async (status: Thread['status']) => { if (!thread) return; try { const r = await fetch(`/api/team/threads/${thread.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, status }) }); if (!r.ok) throw new Error(); setThread({ ...thread, status }) } catch { setError('Unable to update the thread status.') } }
  const createTaskFromThread = async () => { if (!thread) return; try { const r = await fetch('/api/tasks2', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, title: thread.title || thread.rootMessage.body.slice(0, 200), relatedThreadId: thread.id }) }); if (!r.ok) throw new Error(); const task = (await r.json()).task; setThread({ ...thread, relatedTasks: [...(thread.relatedTasks || []), { id: task.id, title: task.title, status: task.status }] }) } catch { setError('Unable to create a linked task.') } }
  const current = conversations.find(c => c.id === selected)
  return <div className="hq-rise"><div className="mb-5"><p className="eyebrow">{project.name} / Communication</p><h1 className="mt-1 text-3xl font-semibold">Team</h1><p className="mt-2 text-sm text-[var(--text-2)]">Project conversations and focused work topics. Chief of Staff execution is not connected in staging.</p></div>{error && <div role="alert" className="mb-4 rounded-lg border border-[var(--down)]/40 bg-[var(--down)]/10 px-3 py-2 text-sm text-[var(--down)]">{error}</div>}<div className="grid min-h-[620px] overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface-1)] lg:grid-cols-[230px_minmax(0,1fr)_320px]">
    <aside className="border-b border-[var(--line)] p-3 lg:border-b-0 lg:border-r"><p className="eyebrow px-2 py-2">Channels & groups</p>{loading ? <p className="p-2 text-sm text-[var(--text-3)]">Loading conversations…</p> : conversations.filter(c => c.type !== 'DIRECT').map(c => <button key={c.id} onClick={() => setSelected(c.id)} className={`mb-1 block w-full rounded-lg px-3 py-2 text-left text-sm ${c.id === selected ? 'bg-white/10 text-white' : 'text-[var(--text-2)] hover:bg-white/5'}`}># {label(c)}</button>)}<p className="eyebrow mt-5 px-2 py-2">Direct messages</p>{conversations.filter(c => c.type === 'DIRECT').map(c => <button key={c.id} onClick={() => setSelected(c.id)} className={`mb-1 block w-full rounded-lg px-3 py-2 text-left text-sm ${c.id === selected ? 'bg-white/10 text-white' : 'text-[var(--text-2)] hover:bg-white/5'}`}>● {label(c)}</button>)}</aside>
    <section className="flex min-w-0 flex-col border-b border-[var(--line)] lg:border-b-0 lg:border-r"><header className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-semibold">{current ? (current.type === 'CHANNEL' ? '# ' : '') + label(current) : 'Select a conversation'}</h2><p className="mt-1 text-xs text-[var(--text-3)]">{current ? `${current._count.messages} message${current._count.messages === 1 ? '' : 's'} · project-scoped` : ''}</p></header><div className="flex-1 space-y-4 overflow-y-auto p-5">{!selected ? <p className="text-sm text-[var(--text-3)]">No conversations are available yet.</p> : messages.length === 0 ? <div className="py-20 text-center text-sm text-[var(--text-3)]">No messages yet. Start the conversation.</div> : messages.map(m => <article key={m.id} className="group"><div className="flex items-baseline justify-between gap-4"><strong className="text-sm">{name(m)}</strong><time className="text-xs text-[var(--text-3)]">{new Date(m.createdAt).toLocaleString()}</time></div><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-[var(--text-2)]">{m.body}</p><button onClick={() => openThread(m)} className="mt-2 text-xs text-[var(--accent)] hover:underline">{m.rootForThread ? `${m.rootForThread._count.replies} replies · View thread` : 'Reply in thread'}</button></article>)}</div>{selected && <form onSubmit={sendMessage} className="border-t border-[var(--line)] p-4"><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Message this conversation" className="min-h-20 w-full resize-none rounded-lg border border-[var(--line)] bg-transparent p-3 text-sm outline-none focus:border-[var(--accent)]"/><div className="mt-2 flex justify-end"><button className="btn-primary px-4 py-2 text-sm" type="submit">Send message</button></div></form>}</section>
    <aside className="flex min-h-72 flex-col bg-black/10">{thread ? <><header className="border-b border-[var(--line)] p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Thread</h2><button onClick={() => setThread(null)} className="text-sm text-[var(--text-3)]">Close</button></div><p className="mt-2 text-sm text-[var(--text-2)]">{thread.title || thread.rootMessage.body}</p><div className="mt-3 flex gap-2"><select aria-label="Thread status" value={thread.status} onChange={e => changeStatus(e.target.value as Thread['status'])} className="rounded border border-[var(--line)] bg-[var(--surface-2)] px-2 py-1 text-xs"><option value="OPEN">Open</option><option value="RESOLVED">Resolved</option><option value="ARCHIVED">Archived</option></select><button onClick={createTaskFromThread} className="btn-ghost px-2 py-1 text-xs">Create Task</button></div>{thread.relatedTasks?.map(task => <p key={task.id} className="mt-2 text-xs text-[var(--accent)]">Related Task: {task.title}</p>)}</header><div className="flex-1 space-y-4 overflow-y-auto p-4"><article><strong className="text-sm">{name(thread.rootMessage)}</strong><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--text-2)]">{thread.rootMessage.body}</p></article>{replies.map(m => <article key={m.id} className="border-l border-[var(--line-strong)] pl-3"><strong className="text-sm">{name(m)}</strong><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--text-2)]">{m.body}</p></article>)}</div><form onSubmit={sendReply} className="border-t border-[var(--line)] p-4"><textarea value={reply} onChange={e => setReply(e.target.value)} placeholder="Reply in thread" className="min-h-16 w-full resize-none rounded-lg border border-[var(--line)] bg-transparent p-2 text-sm"/><button className="btn-primary mt-2 w-full py-2 text-sm">Reply</button></form></> : <div className="m-auto p-7 text-center"><p className="font-medium">Focused topics</p><p className="mt-2 text-sm text-[var(--text-3)]">Open a message thread to keep a topic separate from the main conversation.</p></div>}</aside>
  </div></div>
}
