'use client'
import { useState } from 'react'
type Tool={id:string;tool:{id:string;name:string};_count:{permissions:number}}
type Catalog={id:string;name:string}
type Assignment={id:string;employee:{name:string}}
type Connection={id:string;name:string;status:string;enabled:boolean;projectTool:{tool:{name:string}}}
const levels=['NO_ACCESS','READ','DRAFT','EXECUTE_WITH_APPROVAL','FULL_EXECUTE']
export function ToolWorkspace({project,canManage,initialCatalog,initialTools,initialAssignments,initialConnections,initialExecutions}:{project:{id:string;name:string};canManage:boolean;initialCatalog:Catalog[];initialTools:Tool[];initialAssignments:Assignment[];initialConnections:Connection[];initialExecutions:Array<{id:string;status:string;resultText:string|null;projectTool:{tool:{name:string}}}>}) {
 const [assignment,setAssignment]=useState(''),[tool,setTool]=useState(''),[level,setLevel]=useState('NO_ACCESS'),[notice,setNotice]=useState(''),[driveItemId,setDriveItemId]=useState(''),[driveScopeType,setDriveScopeType]=useState<'FILE'|'FOLDER'>('FILE')
 const drive=initialConnections.find(c=>c.projectTool.tool.name==='Google Drive')
 const request=async(url:string,body:Record<string,unknown>)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,projectId:project.id})});return {r,b:await r.json().catch(()=>({}))}}
 const connect=async()=>{const {r,b}=await request('/api/connections/google-drive/start',{});if(r.ok&&typeof b.authorizationUrl==='string'){window.location.assign(b.authorizationUrl);return}setNotice(b.error==='DRIVE_OAUTH_NOT_CONFIGURED'?'Google Drive OAuth is not configured for this Preview environment yet.':'Google Drive connection could not start.')}
 const disconnect=async()=>{if(!drive)return;const {r}=await request('/api/connections/google-drive/disconnect',{connectionId:drive.id});setNotice(r.ok?'Google Drive disconnected.':'Google Drive disconnect denied.')}
 const scope=async()=>{if(!drive||!driveItemId.trim()){setNotice('Enter the ID of a folder or supported file you explicitly want this project to access.');return}const {r,b}=await request('/api/connections/google-drive/scopes',{connectionId:drive.id,externalId:driveItemId.trim(),type:driveScopeType});setNotice(r.ok?`Scoped ${driveScopeType.toLowerCase()} saved: ${b.scope?.displayName??'selected item'}.`:b.error==='INVALID_DRIVE_ITEM'?'That Drive item was not found or does not match the selected type.':'Drive scope update denied.')}
 const install=async(id:string)=>{const {r}=await request('/api/project-tools',{toolDefinitionId:id});setNotice(r.ok?'Project tool installed. Reload to view project state.':'Unable to install tool.')}
 const grant=async()=>{if(!assignment||!tool)return;const r=await fetch('/api/project-tools/permissions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,employeeProjectAssignmentId:assignment,projectToolId:tool,level})});setNotice(r.ok?'Explicit permission saved. Reload to verify persistence.':'Permission update denied.')}
 const reference=async(action:'read'|'execute')=>{const connector=initialTools.find(t=>t.tool.name==='Reference Connector');if(!connector||!assignment){setNotice('Choose Chief of Staff and ensure the Reference Connector is installed.');return}const {r,b}=await request('/api/tool-executions',{employeeProjectAssignmentId:assignment,projectToolId:connector.id,capabilityKey:action==='read'?'reference_read':'reference_execute',actionKey:action});setNotice(r.ok?`${action==='read'?'Reference read complete.':'Synthetic action is pending approval.'} ${b.execution?.status??''}`:b.error??'Governed action denied.')}
 return <div className="hq-rise"><p className="eyebrow">{project.name} / Tools & Connections</p><h1 className="mt-1 text-3xl font-semibold">Tool controls</h1><p className="mt-2 text-sm text-[var(--text-2)]">Project connections are scoped, credential references stay server-side, and every action passes governance.</p>
 <section className="panel mt-6 p-5"><h2 className="text-lg font-semibold">Google Drive</h2><p className="mt-2 text-sm text-[var(--text-2)]">{drive?`${drive.enabled?drive.status:'Disconnected'} · selected folders and files remain project-scoped.`:'Not Connected · Drive OAuth is configured separately from dashboard sign-in.'}</p>{canManage&&(!drive||!drive.enabled?<button onClick={()=>void connect()} className="btn-primary mt-4 px-3 py-2 text-sm">Connect Google Drive</button>:<><button onClick={()=>void disconnect()} className="btn-ghost mt-4 px-3 py-2 text-sm">Disconnect Google Drive</button><div className="mt-4 grid gap-2 md:grid-cols-[1fr_auto_auto]"><input aria-label="Google Drive item ID" value={driveItemId} onChange={e=>setDriveItemId(e.target.value)} placeholder="Explicit Drive folder or file ID" className="rounded border border-[var(--line)] bg-transparent p-2 text-sm"/><select aria-label="Google Drive scope type" value={driveScopeType} onChange={e=>setDriveScopeType(e.target.value as 'FILE'|'FOLDER')} className="rounded border border-[var(--line)] bg-transparent p-2 text-sm"><option value="FILE">File</option><option value="FOLDER">Folder</option></select><button onClick={()=>void scope()} className="btn-primary px-3 py-2 text-sm">Save scoped item</button></div><p className="mt-2 text-xs text-[var(--text-3)]">Only this selected object is authorized. Folder selection permits listing direct contents; file reads require an explicit file scope.</p></>)}</section>
 <section className="panel mt-6 p-5"><h2 className="text-lg font-semibold">Connections</h2>{initialConnections.length?initialConnections.map(c=><p key={c.id} className="mt-2 text-sm">{c.projectTool.tool.name} · {c.name} · {c.enabled?c.status:'Disabled'}</p>):<p className="mt-2 text-sm text-[var(--text-2)]">Not Connected</p>}</section><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{initialCatalog.map(item=>{const installed=initialTools.find(t=>t.tool.id===item.id);const connected=initialConnections.find(c=>c.projectTool.tool.name===item.name);return <article key={item.id} className="panel p-4"><div className="flex justify-between gap-2"><h2 className="font-semibold">{item.name}</h2><span className="text-xs text-[var(--text-3)]">{connected?.status||(installed?'Not Connected':'Available')}</span></div><p className="mt-3 text-sm text-[var(--text-2)]">{installed?`${installed._count.permissions} explicit employee permission(s)`:'Not installed for this project.'}</p>{canManage&&!installed&&<button onClick={()=>void install(item.id)} className="btn-primary mt-4 px-3 py-1 text-xs">Install metadata</button>}</article>})}</div>
 {canManage&&<section className="panel mt-8 p-5"><h2 className="text-lg font-semibold">Employee permissions & governed reference actions</h2><p className="mt-1 text-sm text-[var(--text-2)]">Default deny. The synthetic reference action never uses a live account.</p><div className="mt-4 grid gap-2 md:grid-cols-4"><select aria-label="Employee" value={assignment} onChange={e=>setAssignment(e.target.value)} className="rounded border border-[var(--line)] bg-transparent p-2"><option value="">Employee</option>{initialAssignments.map(a=><option key={a.id} value={a.id}>{a.employee.name}</option>)}</select><select aria-label="Installed tool" value={tool} onChange={e=>setTool(e.target.value)} className="rounded border border-[var(--line)] bg-transparent p-2"><option value="">Installed tool</option>{initialTools.map(t=><option key={t.id} value={t.id}>{t.tool.name}</option>)}</select><select aria-label="Permission level" value={level} onChange={e=>setLevel(e.target.value)} className="rounded border border-[var(--line)] bg-transparent p-2">{levels.map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>void grant()} className="btn-primary px-4 text-sm">Save explicit grant</button></div><div className="mt-4 flex gap-2"><button onClick={()=>void reference('read')} className="btn-ghost px-3 py-2 text-sm">Run safe reference read</button><button onClick={()=>void reference('execute')} className="btn-primary px-3 py-2 text-sm">Request synthetic action</button></div></section>}<section className="panel mt-8 p-5"><h2 className="text-lg font-semibold">Recent governed executions</h2>{initialExecutions.map(e=><p key={e.id} className="mt-2 text-sm">{e.projectTool.tool.name} · {e.status}{e.resultText?` · ${e.resultText}`:''}</p>)}</section>{notice&&<p className="mt-4 text-sm text-[var(--accent)]">{notice}</p>}</div>
}
