'use client'

import { useState } from 'react'
import { AppWindow, CheckCircle2, ChevronDown, HardDrive, LockKeyhole, Play, PlugZap, ShieldCheck, UserRoundCog } from 'lucide-react'
import { EmptyState, Metric, PageHeader, StatusPill, friendlyLabel } from '@/components/rogeros-ui'

type Tool = { id:string; tool:{id:string;name:string}; _count:{permissions:number} }
type Catalog = { id:string; name:string }
type Assignment = { id:string; employee:{name:string} }
type Connection = { id:string; name:string; status:string; enabled:boolean; projectTool:{tool:{name:string}} }
type Execution = { id:string; status:string; resultText:string|null; projectTool:{tool:{name:string}} }
const levels = ['NO_ACCESS','READ','DRAFT','EXECUTE_WITH_APPROVAL','FULL_EXECUTE']
const levelLabel: Record<string,string> = { NO_ACCESS:'No access', READ:'View only', DRAFT:'Prepare drafts', EXECUTE_WITH_APPROVAL:'Use with approval', FULL_EXECUTE:'Use independently' }

export function ToolWorkspace({ project, canManage, initialCatalog, initialTools, initialAssignments, initialConnections, initialExecutions }: { project:{id:string;name:string}; canManage:boolean; initialCatalog:Catalog[]; initialTools:Tool[]; initialAssignments:Assignment[]; initialConnections:Connection[]; initialExecutions:Execution[] }) {
  const [assignment,setAssignment] = useState(''); const [tool,setTool] = useState(''); const [level,setLevel] = useState('NO_ACCESS'); const [notice,setNotice] = useState(''); const [driveItemId,setDriveItemId] = useState(''); const [driveScopeType,setDriveScopeType] = useState<'FILE'|'FOLDER'>('FILE')
  const drive = initialConnections.find(connection => connection.projectTool.tool.name === 'Google Drive')
  const request = async (url:string,body:Record<string,unknown>) => { const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,projectId:project.id})}); return { response, data:await response.json().catch(()=>({})) } }
  const connect = async () => { const {response,data}=await request('/api/connections/google-drive/start',{}); if(response.ok&&typeof data.authorizationUrl==='string'){window.location.assign(data.authorizationUrl);return} setNotice(data.error==='DRIVE_OAUTH_NOT_CONFIGURED'?'Google Drive is not available in this environment yet.':'Google Drive could not be connected.') }
  const disconnect = async () => { if(!drive)return; const {response}=await request('/api/connections/google-drive/disconnect',{connectionId:drive.id}); setNotice(response.ok?'Google Drive disconnected.':'Google Drive could not be disconnected.') }
  const saveScope = async () => { if(!drive||!driveItemId.trim()){setNotice('Choose a Drive file or folder first.');return} const {response,data}=await request('/api/connections/google-drive/scopes',{connectionId:drive.id,externalId:driveItemId.trim(),type:driveScopeType}); setNotice(response.ok?`${data.scope?.displayName??'Drive item'} is now available to this project.`:data.error==='INVALID_DRIVE_ITEM'?'That Drive item was not found or does not match the selected type.':'The Drive selection could not be saved.') }
  const readDrive = async () => { const projectTool=initialTools.find(item=>item.tool.name==='Google Drive'); if(!drive||!projectTool||!assignment||!driveItemId.trim()){setNotice('Choose an employee and an approved Drive file first.');return} const {response,data}=await request('/api/tool-executions',{employeeProjectAssignmentId:assignment,projectToolId:projectTool.id,capabilityKey:'drive_read',actionKey:'read',fileId:driveItemId.trim()}); setNotice(response.ok&&data.execution?.resultText?data.execution.resultText:data.error??'The Drive read did not complete.') }
  const install = async (id:string) => { const {response}=await request('/api/project-tools',{toolDefinitionId:id}); setNotice(response.ok?'App added to this project. Refresh to view it.':'This app could not be added.') }
  const grant = async () => { if(!assignment||!tool){setNotice('Choose an employee and an app first.');return} const response=await fetch('/api/project-tools/permissions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,employeeProjectAssignmentId:assignment,projectToolId:tool,level})}); setNotice(response.ok?'Employee access saved. Refresh to verify it.':'Employee access could not be updated.') }
  const reference = async (action:'read'|'execute') => { const connector=initialTools.find(item=>item.tool.name==='Reference Connector'); if(!connector||!assignment){setNotice('Choose an employee and make sure the reference app is available.');return} const {response,data}=await request('/api/tool-executions',{employeeProjectAssignmentId:assignment,projectToolId:connector.id,capabilityKey:action==='read'?'reference_read':'reference_execute',actionKey:action}); setNotice(response.ok?`${action==='read'?'Safe check complete.':'Approval requested.'} ${friendlyLabel(data.execution?.status??'')}`:data.error??'This action was denied.') }

  return <div className="hq-rise">
    <PageHeader eyebrow={`${project.name} · Company`} title="Tools" description="Connect the apps your company uses and decide exactly what each employee may do." />
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Available apps" value={initialCatalog.length}/><Metric label="Added to project" value={initialTools.length}/><Metric label="Connected accounts" value={initialConnections.filter(item=>item.enabled).length} tone={initialConnections.some(item=>item.enabled)?'good':'neutral'}/></div>
    {notice && <div role="status" className="mt-4 rounded-xl border border-[rgba(126,208,173,.2)] bg-[rgba(126,208,173,.07)] px-4 py-3 text-[11px] text-[var(--ros-muted)]">{notice}</div>}

    <section className="panel mt-6 overflow-hidden"><div className="flex flex-wrap items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[rgba(126,208,173,.1)] text-[var(--ros-accent)]"><HardDrive className="w-5"/></span><div className="min-w-[200px] flex-1"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">Google Drive</h2><StatusPill tone={drive?.enabled?'good':'neutral'}>{drive?.enabled?'Connected':'Not connected'}</StatusPill></div><p className="mt-1.5 text-[10px] leading-5 text-[var(--ros-faint)]">Give this project read-only access to specific files and folders. Nothing else in your Drive is exposed.</p></div>{canManage&&(!drive||!drive.enabled?<button onClick={()=>void connect()} className="btn-primary inline-flex items-center gap-2 px-3 py-2 text-xs"><PlugZap className="w-3.5"/> Connect Drive</button>:<button onClick={()=>void disconnect()} className="btn-ghost px-3 py-2 text-xs">Disconnect</button>)}</div>
      {canManage&&drive?.enabled&&<details className="border-t border-[var(--ros-line)]"><summary className="flex cursor-pointer list-none items-center justify-between px-5 py-3 text-[10px] font-medium text-[var(--ros-muted)]">Choose accessible files or folders <ChevronDown className="w-3.5"/></summary><div className="grid gap-3 border-t border-[var(--ros-line)] bg-black/[.08] p-5 md:grid-cols-[minmax(0,1fr)_140px_auto]"><input aria-label="Google Drive item ID" value={driveItemId} onChange={event=>setDriveItemId(event.target.value)} placeholder="Paste a Google Drive file or folder ID" className="px-3 py-2.5 text-xs"/><select aria-label="Google Drive scope type" value={driveScopeType} onChange={event=>setDriveScopeType(event.target.value as 'FILE'|'FOLDER')} className="px-3 py-2.5 text-xs"><option value="FILE">Single file</option><option value="FOLDER">Folder</option></select><button onClick={()=>void saveScope()} className="btn-primary px-3 py-2 text-xs">Allow access</button><p className="text-[9px] leading-4 text-[var(--ros-faint)] md:col-span-3">A folder permits listing its direct contents. Reading a file still requires explicit file access.</p></div></details>}
    </section>

    <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">App library</p><h2 className="mt-1 text-lg font-semibold">Apps for {project.name}</h2></div><StatusPill>{initialCatalog.length} available</StatusPill></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{initialCatalog.map(item=>{const installed=initialTools.find(entry=>entry.tool.id===item.id); const connected=initialConnections.find(entry=>entry.projectTool.tool.name===item.name); return <article key={item.id} className="panel panel-interactive p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.035] text-[var(--ros-muted)]"><AppWindow className="w-4"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="truncate text-xs font-semibold">{item.name}</h3><StatusPill tone={connected?.enabled?'good':'neutral'}>{connected?.enabled?'Connected':installed?'Added':'Available'}</StatusPill></div><p className="mt-2 text-[10px] leading-4 text-[var(--ros-faint)]">{installed?`${installed._count.permissions} employee access rule${installed._count.permissions===1?'':'s'}`:'Add this app before granting employee access.'}</p>{canManage&&!installed&&<button onClick={()=>void install(item.id)} className="btn-ghost mt-3 px-3 py-1.5 text-[10px]">Add to project</button>}</div></div></article>})}</div></section>

    {canManage&&<section className="panel mt-8 p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[rgba(126,208,173,.1)] text-[var(--ros-accent)]"><UserRoundCog className="w-4"/></span><div><h2 className="text-sm font-semibold">Employee access</h2><p className="mt-1 text-[10px] text-[var(--ros-faint)]">Employees begin with no access. Grant only what their role needs.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-4"><select aria-label="Employee" value={assignment} onChange={event=>setAssignment(event.target.value)} className="px-3 py-2.5 text-xs"><option value="">Choose employee</option>{initialAssignments.map(item=><option key={item.id} value={item.id}>{item.employee.name}</option>)}</select><select aria-label="Installed tool" value={tool} onChange={event=>setTool(event.target.value)} className="px-3 py-2.5 text-xs"><option value="">Choose app</option>{initialTools.map(item=><option key={item.id} value={item.id}>{item.tool.name}</option>)}</select><select aria-label="Permission level" value={level} onChange={event=>setLevel(event.target.value)} className="px-3 py-2.5 text-xs">{levels.map(value=><option key={value} value={value}>{levelLabel[value]}</option>)}</select><button onClick={()=>void grant()} className="btn-primary px-4 py-2 text-xs">Save access</button></div><details className="mt-5 border-t border-[var(--ros-line)] pt-3"><summary className="cursor-pointer text-[10px] text-[var(--ros-faint)]">Advanced permission validation</summary><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void reference('read')} className="btn-ghost inline-flex items-center gap-2 px-3 py-2 text-[10px]"><CheckCircle2 className="w-3"/> Check read access</button><button onClick={()=>void reference('execute')} className="btn-ghost inline-flex items-center gap-2 px-3 py-2 text-[10px]"><ShieldCheck className="w-3"/> Test approval gate</button>{drive?.enabled&&<button onClick={()=>void readDrive()} className="btn-ghost inline-flex items-center gap-2 px-3 py-2 text-[10px]"><HardDrive className="w-3"/> Check Drive access</button>}</div></details></section>}

    <section className="mt-8"><div className="mb-3 flex items-center gap-2"><Play className="w-3.5 text-[var(--ros-faint)]"/><h2 className="text-sm font-semibold">Recent app activity</h2></div>{initialExecutions.length?<div className="panel divide-y divide-[var(--ros-line)]">{initialExecutions.map(item=><div key={item.id} className="flex items-center gap-3 px-4 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/[.035] text-[var(--ros-faint)]"><LockKeyhole className="w-3.5"/></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium">{item.projectTool.tool.name}</p>{item.resultText&&<p className="mt-1 line-clamp-1 text-[9px] text-[var(--ros-faint)]">{item.resultText}</p>}</div><StatusPill tone={item.status==='SUCCEEDED'||item.status==='COMPLETED'?'good':item.status==='FAILED'?'bad':'warn'}>{friendlyLabel(item.status)}</StatusPill></div>)}</div>:<section className="panel"><EmptyState icon={<Play/>} title="No app activity yet" description="When an employee uses an approved app, its outcome will appear here."/></section>}</section>
  </div>
}
